In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import yfinance as yf

In [2]:
# raw = yf.download("AAPL", start="2026-01-01", end="2026-06-30")
raw = yf.download("NVDA", period="1y", interval="1d", multi_level_index=False)

[*********************100%***********************]  1 of 1 completed

In [3]:
raw.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 251 entries, 2025-07-09 to 2026-07-08
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Close   251 non-null    float64
 1   High    251 non-null    float64
 2   Low     251 non-null    float64
 3   Open    251 non-null    float64
 4   Volume  251 non-null    int64
dtypes: float64(4), int64(1)
memory usage: 11.8 KB

In [4]:
raw.isna().sum()

Close     0
High      0
Low       0
Open      0
Volume    0
dtype: int64

In [5]:
raw.tail()

                 Close        High         Low        Open     Volume
Date
2026-07-01  197.580002  199.850006  193.449997  196.199997  146147600
2026-07-02  194.830002  200.059998  192.350006  197.139999  142068700
2026-07-06  195.550003  197.550003  193.990005  194.419998  108999000
2026-07-07  196.929993  198.410004  191.139999  192.369995  124154600
2026-07-08  204.119995  205.149994  195.104996  195.130005  145806099

In [6]:
df = raw.copy()

In [7]:
df.describe()

            Close        High         Low        Open        Volume
count  251.000000  251.000000  251.000000  251.000000  2.510000e+02
mean   188.068052  190.743185  185.306779  188.187643  1.741888e+08
std     13.943740   14.471331   13.585539   14.046502  4.561505e+07
min    162.852936  164.392673  161.133220  161.193208  6.552850e+07
25%    178.320389  181.055099  175.830381  178.235405  1.439836e+08
50%    184.879990  187.209440  182.030014  184.749708  1.664767e+08
75%    195.549706  198.014653  192.009473  195.134290  1.916750e+08
max    235.740005  236.539993  229.300003  229.869995  3.608079e+08

In [8]:
df.shape

(251, 5)

In [9]:
df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 251 entries, 2025-07-09 to 2026-07-08
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Close   251 non-null    float64
 1   High    251 non-null    float64
 2   Low     251 non-null    float64
 3   Open    251 non-null    float64
 4   Volume  251 non-null    int64
dtypes: float64(4), int64(1)
memory usage: 11.8 KB

In [10]:
df.head()

                 Close        High         Low        Open     Volume
Date
2025-07-09  162.852936  164.392673  161.133220  161.193208  183656400
2025-07-10  164.072739  164.472666  161.583147  164.292703  167704100
2025-07-11  164.892593  167.862101  163.442837  163.692796  193633300
2025-07-14  164.042740  165.462502  161.993078  165.342512  136975800
2025-07-15  170.671631  172.371345  169.171880  171.161555  230627400

In [11]:
df.tail()

                 Close        High         Low        Open     Volume
Date
2026-07-01  197.580002  199.850006  193.449997  196.199997  146147600
2026-07-02  194.830002  200.059998  192.350006  197.139999  142068700
2026-07-06  195.550003  197.550003  193.990005  194.419998  108999000
2026-07-07  196.929993  198.410004  191.139999  192.369995  124154600
2026-07-08  204.119995  205.149994  195.104996  195.130005  145806099

In [12]:
df['Close'].agg(['max', 'min', 'mean']).map('{:.0f}'.format)

max     236
min     163
mean    188
Name: Close, dtype: str

In [13]:
df['Volume'].agg(['mean', 'median', 'std']).map('{:,.0f}'.format)

mean      174,188,807
median    166,476,700
std        45,615,050
Name: Volume, dtype: str

In [14]:
df['Volume'].agg(['mean', 'median', 'std']).map('{:,.03f}'.format)

mean      174,188,807.167
median    166,476,700.000
std        45,615,050.446
Name: Volume, dtype: str

In [15]:
print(f"{((df['High'] - df['Low']).mean()):.0f}")

5

In [16]:
new = df[['Close', 'Volume']]

In [17]:
new

                 Close     Volume
Date
2025-07-09  162.852936  183656400
2025-07-10  164.072739  167704100
2025-07-11  164.892593  193633300
2025-07-14  164.042740  136975800
2025-07-15  170.671631  230627400
...                ...        ...
2026-07-01  197.580002  146147600
2026-07-02  194.830002  142068700
2026-07-06  195.550003  108999000
2026-07-07  196.929993  124154600
2026-07-08  204.119995  145806099

[251 rows x 2 columns]

In [18]:
df.tail(10)

                 Close        High         Low        Open     Volume
Date
2026-06-24  199.000000  201.669998  196.580002  200.119995  151810700
2026-06-25  195.740005  200.800003  192.130005  200.080002  149550000
2026-06-26  192.529999  195.550003  191.220001  193.119995  179304100
2026-06-29  194.970001  196.179993  189.800003  193.850006  148835700
2026-06-30  200.089996  200.630005  195.110001  197.240005  166476700
2026-07-01  197.580002  199.850006  193.449997  196.199997  146147600
2026-07-02  194.830002  200.059998  192.350006  197.139999  142068700
2026-07-06  195.550003  197.550003  193.990005  194.419998  108999000
2026-07-07  196.929993  198.410004  191.139999  192.369995  124154600
2026-07-08  204.119995  205.149994  195.104996  195.130005  145806099

In [19]:
df.iloc[-10:]

                 Close        High         Low        Open     Volume
Date
2026-06-24  199.000000  201.669998  196.580002  200.119995  151810700
2026-06-25  195.740005  200.800003  192.130005  200.080002  149550000
2026-06-26  192.529999  195.550003  191.220001  193.119995  179304100
2026-06-29  194.970001  196.179993  189.800003  193.850006  148835700
2026-06-30  200.089996  200.630005  195.110001  197.240005  166476700
2026-07-01  197.580002  199.850006  193.449997  196.199997  146147600
2026-07-02  194.830002  200.059998  192.350006  197.139999  142068700
2026-07-06  195.550003  197.550003  193.990005  194.419998  108999000
2026-07-07  196.929993  198.410004  191.139999  192.369995  124154600
2026-07-08  204.119995  205.149994  195.104996  195.130005  145806099

In [20]:
new.loc[new['Close'] > new['Close'].quantile(0.9), 'Close'].index

DatetimeIndex(['2026-04-27', '2026-04-28', '2026-04-29', '2026-05-07',
               '2026-05-08', '2026-05-11', '2026-05-12', '2026-05-13',
               '2026-05-14', '2026-05-15', '2026-05-18', '2026-05-19',
               '2026-05-20', '2026-05-21', '2026-05-22', '2026-05-26',
               '2026-05-27', '2026-05-28', '2026-05-29', '2026-06-01',
               '2026-06-02', '2026-06-03', '2026-06-04', '2026-06-15',
               '2026-06-18'],
              dtype='datetime64[s]', name='Date', freq=None)

In [21]:
len(new.loc[new['Close'] > new['Close'].quantile(0.9), 'Close'].index)

25

In [22]:
print(f"종가 {new['Close'].quantile(0.9):.2f} 이상인 날: {len(new.loc[new['Close'] > new['Close'].quantile(0.9), 'Close'])}일")

종가 208.65 이상인 날: 25일

In [23]:
new.loc[new['Volume'] > new['Volume'].mean()]

                 Close     Volume
Date
2025-07-09  162.852936  183656400
2025-07-11  164.892593  193633300
2025-07-15  170.671631  230627400
2025-07-22  167.002258  193114300
2025-07-30  179.240219  174312200
...                ...        ...
2026-06-02  222.820007  193362900
2026-06-05  205.100006  219655500
2026-06-09  208.190002  180962500
2026-06-18  210.690002  241272000
2026-06-26  192.529999  179304100

[108 rows x 2 columns]

In [24]:
new.sort_values('Volume', ascending=False)

                 Close     Volume
Date
2026-02-26  184.879990  360807900
2025-11-21  178.860367  346926200
2025-11-20  180.620163  343504800
2025-12-19  180.980209  324925900
2025-11-25  177.800476  320600300
...                ...        ...
2026-04-21  199.880005  107945300
2026-04-06  177.639999  107564300
2026-04-22  202.500000  107501000
2025-12-30  187.529846   97687300
2025-12-24  188.599792   65528500

[251 rows x 2 columns]

In [25]:
df['Daily_Change'] = (df['Close'] - df['Open']).round(3)

In [26]:
df[['Open', 'Close', 'Daily_Change']].head()

                  Open       Close  Daily_Change
Date
2025-07-09  161.193208  162.852936          1.66
2025-07-10  164.292703  164.072739         -0.22
2025-07-11  163.692796  164.892593          1.20
2025-07-14  165.342512  164.042740         -1.30
2025-07-15  171.161555  170.671631         -0.49

In [27]:
new.drop(columns='Daily_Change', inplace=True)

KeyError: "['Daily_Change'] not found in axis"

In [ ]:
new

                 Close     Volume
Date
2025-07-08  159.973419  138133000
2025-07-09  162.852936  183656400
2025-07-10  164.072739  167704100
2025-07-11  164.892593  193633300
2025-07-14  164.042740  136975800
...                ...        ...
2026-06-30  200.089996  166476700
2026-07-01  197.580002  146147600
2026-07-02  194.830002  142068700
2026-07-06  195.550003  108999000
2026-07-07  196.929993  122966441

[251 rows x 2 columns]

In [ ]:
df['Change_Rate'] = ((df['Close'] - df['Open'])/df['Open']*100).round(3)

In [ ]:
df

,Close,High,Low,Open,Volume,Daily_Change,Change_Rate,Year,Month,Weekday
Date,,,,,,,,,,
2025-07-08,159.973419,160.193384,158.363686,159.303532,138133000,0.669887,0.421,2025,7,tue
2025-07-09,162.852936,164.392673,161.133220,161.193208,183656400,1.659728,1.030,2025,7,wed
2025-07-10,164.072739,164.472666,161.583147,164.292703,167704100,-0.219965,-0.134,2025,7,thu
2025-07-11,164.892593,167.862101,163.442837,163.692796,193633300,1.199798,0.733,2025,7,fri
2025-07-14,164.042740,165.462502,161.993078,165.342512,136975800,-1.299772,-0.786,2025,7,mon
...,...,...,...,...,...,...,...,...,...,...
2026-06-30,200.089996,200.630005,195.110001,197.240005,166476700,2.849991,1.445,2026,6,tue
2026-07-01,197.580002,199.850006,193.449997,196.199997,146147600,1.380005,0.703,2026,7,wed
2026-07-02,194.830002,200.059998,192.350006,197.139999,142068700,-2.309998,-1.172,2026,7,thu
2026-07-06,195.550003,197.550003,193.990005,194.419998,108999000,1.130005,0.581,2026,7,mon
2026-07-07,196.929993,198.410004,191.149994,192.369995,122966441,4.559998,2.370,2026,7,tue

In [28]:
df.index.day_name()

Index(['Wednesday', 'Thursday', 'Friday', 'Monday', 'Tuesday', 'Wednesday',
       'Thursday', 'Friday', 'Monday', 'Tuesday',
       ...
       'Wednesday', 'Thursday', 'Friday', 'Monday', 'Tuesday', 'Wednesday',
       'Thursday', 'Monday', 'Tuesday', 'Wednesday'],
      dtype='str', name='Date', length=251)

In [29]:
df.index.weekday

Index([2, 3, 4, 0, 1, 2, 3, 4, 0, 1,
       ...
       2, 3, 4, 0, 1, 2, 3, 0, 1, 2],
      dtype='int32', name='Date', length=251)

In [30]:
df['Year'] = df.index.year

In [31]:
df['Month'] = df.index.month

In [32]:
df['Weekday'] = df.index.weekday

In [33]:
df

,Close,High,Low,Open,Volume,Daily_Change,Year,Month,Weekday
Date,,,,,,,,,
2025-07-09,162.852936,164.392673,161.133220,161.193208,183656400,1.66,2025,7,2
2025-07-10,164.072739,164.472666,161.583147,164.292703,167704100,-0.22,2025,7,3
2025-07-11,164.892593,167.862101,163.442837,163.692796,193633300,1.20,2025,7,4
2025-07-14,164.042740,165.462502,161.993078,165.342512,136975800,-1.30,2025,7,0
2025-07-15,170.671631,172.371345,169.171880,171.161555,230627400,-0.49,2025,7,1
...,...,...,...,...,...,...,...,...,...
2026-07-01,197.580002,199.850006,193.449997,196.199997,146147600,1.38,2026,7,2
2026-07-02,194.830002,200.059998,192.350006,197.139999,142068700,-2.31,2026,7,3
2026-07-06,195.550003,197.550003,193.990005,194.419998,108999000,1.13,2026,7,0
2026-07-07,196.929993,198.410004,191.139999,192.369995,124154600,4.56,2026,7,1
2026-07-08,204.119995,205.149994,195.104996,195.130005,145806099,8.99,2026,7,2

In [36]:
df['day_name'] = df.index.day_name()

In [37]:
df

,Close,High,Low,Open,Volume,Daily_Change,Year,Month,Weekday,day_name
Date,,,,,,,,,,
2025-07-09,162.852936,164.392673,161.133220,161.193208,183656400,1.66,2025,7,2,Wednesday
2025-07-10,164.072739,164.472666,161.583147,164.292703,167704100,-0.22,2025,7,3,Thursday
2025-07-11,164.892593,167.862101,163.442837,163.692796,193633300,1.20,2025,7,4,Friday
2025-07-14,164.042740,165.462502,161.993078,165.342512,136975800,-1.30,2025,7,0,Monday
2025-07-15,170.671631,172.371345,169.171880,171.161555,230627400,-0.49,2025,7,1,Tuesday
...,...,...,...,...,...,...,...,...,...,...
2026-07-01,197.580002,199.850006,193.449997,196.199997,146147600,1.38,2026,7,2,Wednesday
2026-07-02,194.830002,200.059998,192.350006,197.139999,142068700,-2.31,2026,7,3,Thursday
2026-07-06,195.550003,197.550003,193.990005,194.419998,108999000,1.13,2026,7,0,Monday
2026-07-07,196.929993,198.410004,191.139999,192.369995,124154600,4.56,2026,7,1,Tuesday
2026-07-08,204.119995,205.149994,195.104996,195.130005,145806099,8.99,2026,7,2,Wednesday

In [38]:
temp = ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']

In [39]:
temp

['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']

In [40]:
dict = {num:item for num, item in enumerate(temp)}

In [41]:
dict

{0: 'mon', 1: 'tue', 2: 'wed', 3: 'thu', 4: 'fri', 5: 'sat', 6: 'sun'}

In [42]:
df['Weekday'].unique()

array([2, 3, 4, 0, 1], dtype=int32)

In [43]:
df['Weekday_name'] = df['Weekday'].map(dict)

In [44]:
df

,Close,High,Low,Open,Volume,Daily_Change,Year,Month,Weekday,day_name,Weekday_name
Date,,,,,,,,,,,
2025-07-09,162.852936,164.392673,161.133220,161.193208,183656400,1.66,2025,7,2,Wednesday,wed
2025-07-10,164.072739,164.472666,161.583147,164.292703,167704100,-0.22,2025,7,3,Thursday,thu
2025-07-11,164.892593,167.862101,163.442837,163.692796,193633300,1.20,2025,7,4,Friday,fri
2025-07-14,164.042740,165.462502,161.993078,165.342512,136975800,-1.30,2025,7,0,Monday,mon
2025-07-15,170.671631,172.371345,169.171880,171.161555,230627400,-0.49,2025,7,1,Tuesday,tue
...,...,...,...,...,...,...,...,...,...,...,...
2026-07-01,197.580002,199.850006,193.449997,196.199997,146147600,1.38,2026,7,2,Wednesday,wed
2026-07-02,194.830002,200.059998,192.350006,197.139999,142068700,-2.31,2026,7,3,Thursday,thu
2026-07-06,195.550003,197.550003,193.990005,194.419998,108999000,1.13,2026,7,0,Monday,mon
2026-07-07,196.929993,198.410004,191.139999,192.369995,124154600,4.56,2026,7,1,Tuesday,tue
2026-07-08,204.119995,205.149994,195.104996,195.130005,145806099,8.99,2026,7,2,Wednesday,wed

In [45]:
df.drop(columns='Weekday_name', inplace=True)

In [46]:
df.head()

,Close,High,Low,Open,Volume,Daily_Change,Year,Month,Weekday,day_name
Date,,,,,,,,,,
2025-07-09,162.852936,164.392673,161.133220,161.193208,183656400,1.66,2025,7,2,Wednesday
2025-07-10,164.072739,164.472666,161.583147,164.292703,167704100,-0.22,2025,7,3,Thursday
2025-07-11,164.892593,167.862101,163.442837,163.692796,193633300,1.20,2025,7,4,Friday
2025-07-14,164.042740,165.462502,161.993078,165.342512,136975800,-1.30,2025,7,0,Monday
2025-07-15,170.671631,172.371345,169.171880,171.161555,230627400,-0.49,2025,7,1,Tuesday

In [51]:
df['day_name'] = df['day_name'].map(lambda x: x[0:3].lower())

In [52]:
df.head()

,Close,High,Low,Open,Volume,Daily_Change,Year,Month,Weekday,day_name
Date,,,,,,,,,,
2025-07-09,162.852936,164.392673,161.133220,161.193208,183656400,1.66,2025,7,2,wed
2025-07-10,164.072739,164.472666,161.583147,164.292703,167704100,-0.22,2025,7,3,thu
2025-07-11,164.892593,167.862101,163.442837,163.692796,193633300,1.20,2025,7,4,fri
2025-07-14,164.042740,165.462502,161.993078,165.342512,136975800,-1.30,2025,7,0,mon
2025-07-15,170.671631,172.371345,169.171880,171.161555,230627400,-0.49,2025,7,1,tue

In [239]:
df.groupby('Month')[['Close', 'Volume']].agg({'Close':'mean', 'Volume':'sum'})

            Close      Volume
Month
1      186.711894  3292228600
2      185.701528  3745445000
3      178.552773  4027150800
4      195.198572  3129548700
5      215.458001  3324840700
6      206.629524  3424306300
7      175.166366  3448763341
8      179.384468  3608891200
9      175.721304  3890495300
10     188.232375  4031017400
11     187.962520  4160148300
12     182.324673  3629693700

In [66]:
df.groupby('Month').agg({'Close':'mean', 'Volume':'sum'})

            Close      Volume
Month
1      186.711894  3292228600
2      185.701528  3745445000
3      178.552773  4027150800
4      195.198572  3129548700
5      215.458001  3324840700
6      206.629524  3424306300
7      177.173028  3457624599
8      179.384471  3608891200
9      175.721304  3890495300
10     188.232375  4031017400
11     187.962520  4160148300
12     182.324673  3629693700

In [67]:
df.groupby('Year')['Close'].agg(['max', 'min'])

             max         min
Year
2025  207.017273  162.852936
2026  235.740005  165.169998

In [68]:
df.groupby('Year').agg({'High':'max', 'Low':'min'})

            High         Low
Year
2025  212.166717  161.133220
2026  236.539993  164.270004

In [78]:
df['Change_Rate'] = ((df['Close'] - df['Open']) / df['Open']*100).round(2)

In [79]:
df.head()

,Close,High,Low,Open,Volume,Daily_Change,Year,Month,Weekday,day_name,Change_Rate
Date,,,,,,,,,,,
2025-07-09,162.852936,164.392673,161.133220,161.193208,183656400,1.66,2025,7,2,wed,1.03
2025-07-10,164.072739,164.472666,161.583147,164.292703,167704100,-0.22,2025,7,3,thu,-0.13
2025-07-11,164.892593,167.862101,163.442837,163.692796,193633300,1.20,2025,7,4,fri,0.73
2025-07-14,164.042740,165.462502,161.993078,165.342512,136975800,-1.30,2025,7,0,mon,-0.79
2025-07-15,170.671631,172.371345,169.171880,171.161555,230627400,-0.49,2025,7,1,tue,-0.29

In [80]:
df['Price_up'] = (df['Close'] > df['Open']).astype(int)

In [81]:
df

,Close,High,Low,Open,Volume,Daily_Change,Year,Month,Weekday,day_name,Change_Rate,Price_up
Date,,,,,,,,,,,,
2025-07-09,162.852936,164.392673,161.133220,161.193208,183656400,1.66,2025,7,2,wed,1.03,1
2025-07-10,164.072739,164.472666,161.583147,164.292703,167704100,-0.22,2025,7,3,thu,-0.13,0
2025-07-11,164.892593,167.862101,163.442837,163.692796,193633300,1.20,2025,7,4,fri,0.73,1
2025-07-14,164.042740,165.462502,161.993078,165.342512,136975800,-1.30,2025,7,0,mon,-0.79,0
2025-07-15,170.671631,172.371345,169.171880,171.161555,230627400,-0.49,2025,7,1,tue,-0.29,0
...,...,...,...,...,...,...,...,...,...,...,...,...
2026-07-01,197.580002,199.850006,193.449997,196.199997,146147600,1.38,2026,7,2,wed,0.70,1
2026-07-02,194.830002,200.059998,192.350006,197.139999,142068700,-2.31,2026,7,3,thu,-1.17,0
2026-07-06,195.550003,197.550003,193.990005,194.419998,108999000,1.13,2026,7,0,mon,0.58,1
2026-07-07,196.929993,198.410004,191.139999,192.369995,124154600,4.56,2026,7,1,tue,2.37,1
2026-07-08,204.119995,205.149994,195.104996,195.130005,145806099,8.99,2026,7,2,wed,4.61,1

In [82]:
pd.concat([df['Price_up'].head(10), df['Price_up'].shift().head(10)], axis=1)

            Price_up  Price_up
Date
2025-07-09         1       NaN
2025-07-10         0       1.0
2025-07-11         1       0.0
2025-07-14         0       1.0
2025-07-15         0       0.0
2025-07-16         1       0.0
2025-07-17         1       1.0
2025-07-18         0       1.0
2025-07-21         0       0.0
2025-07-22         0       0.0

In [83]:
df['Price_up'].groupby(df['Price_up'] != df['Price_up'].shift()).cumsum()

Date
2025-07-09     1
2025-07-10     1
2025-07-11     2
2025-07-14     2
2025-07-15     0
              ..
2026-07-01    65
2026-07-02    60
2026-07-06    61
2026-07-07    66
2026-07-08    67
Name: Price_up, Length: 251, dtype: int64

In [84]:
temp = ''.join(df['Price_up'].values.astype(str))
temp

'10100110001101010010101110101011111000101011101100111001111100101101000100011110000000110001101001100100101001001001011110000010011010011101110000011000010111110011110111001001001100010111011111111010111000001111111001100001010010000111001000001110111'

In [87]:
x = temp.split('0')
x

['1',
 '1',
 '',
 '11',
 '',
 '',
 '11',
 '1',
 '1',
 '',
 '1',
 '1',
 '111',
 '1',
 '1',
 '11111',
 '',
 '',
 '1',
 '1',
 '111',
 '11',
 '',
 '111',
 '',
 '11111',
 '',
 '1',
 '11',
 '1',
 '',
 '',
 '1',
 '',
 '',
 '1111',
 '',
 '',
 '',
 '',
 '',
 '',
 '11',
 '',
 '',
 '11',
 '1',
 '',
 '11',
 '',
 '1',
 '',
 '1',
 '1',
 '',
 '1',
 '',
 '1',
 '',
 '1',
 '1111',
 '',
 '',
 '',
 '',
 '1',
 '',
 '11',
 '1',
 '',
 '111',
 '111',
 '',
 '',
 '',
 '',
 '11',
 '',
 '',
 '',
 '1',
 '11111',
 '',
 '1111',
 '111',
 '',
 '1',
 '',
 '1',
 '',
 '11',
 '',
 '',
 '1',
 '111',
 '11111111',
 '1',
 '111',
 '',
 '',
 '',
 '',
 '1111111',
 '',
 '11',
 '',
 '',
 '',
 '1',
 '1',
 '',
 '1',
 '',
 '',
 '',
 '111',
 '',
 '1',
 '',
 '',
 '',
 '',
 '111',
 '111']

In [88]:
length = 0

for i in x:
    if len(i) > length:
        length = len(i)

print('Max: ', length)

Max:  8

In [89]:
x = df['Price_up'].values
x

array([1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 1])

In [90]:

num = 0
max = 0
max_idx = []

for idx, i in enumerate(x):
    if i == 1:
        num += 1
        if num > max:
            max = num
            max_idx.append(idx)
    else:
        num = 0

In [91]:
max

8

In [92]:
max_idx

[0, 6, 24, 33, 34, 194, 195, 196]

In [93]:
x[190:198]

array([1, 1, 1, 1, 1, 1, 1, 0])

In [94]:
arr = df['Price_up'].values

In [95]:
max_len = 0       # 가장 긴 길이
max_start = -1    # 가장 긴 구간의 시작 인덱스

current_len = 0
current_start = 0

for i, x in enumerate(arr):
    if x == 1:
        if current_len == 0:
            current_start = i      # 새로운 연속 구간 시작
        current_len += 1

        if current_len > max_len:
            max_len = current_len
            max_start = current_start
    else:
        current_len = 0

print(f'최대 연속 개수 : {max_len}')
print(f'시작 인덱스   : {max_start}')
print(f'끝 인덱스     : {max_start + max_len - 1}')

최대 연속 개수 : 8
시작 인덱스   : 189
끝 인덱스     : 196

In [96]:
df

,Close,High,Low,Open,Volume,Daily_Change,Year,Month,Weekday,day_name,Change_Rate,Price_up
Date,,,,,,,,,,,,
2025-07-09,162.852936,164.392673,161.133220,161.193208,183656400,1.66,2025,7,2,wed,1.03,1
2025-07-10,164.072739,164.472666,161.583147,164.292703,167704100,-0.22,2025,7,3,thu,-0.13,0
2025-07-11,164.892593,167.862101,163.442837,163.692796,193633300,1.20,2025,7,4,fri,0.73,1
2025-07-14,164.042740,165.462502,161.993078,165.342512,136975800,-1.30,2025,7,0,mon,-0.79,0
2025-07-15,170.671631,172.371345,169.171880,171.161555,230627400,-0.49,2025,7,1,tue,-0.29,0
...,...,...,...,...,...,...,...,...,...,...,...,...
2026-07-01,197.580002,199.850006,193.449997,196.199997,146147600,1.38,2026,7,2,wed,0.70,1
2026-07-02,194.830002,200.059998,192.350006,197.139999,142068700,-2.31,2026,7,3,thu,-1.17,0
2026-07-06,195.550003,197.550003,193.990005,194.419998,108999000,1.13,2026,7,0,mon,0.58,1
2026-07-07,196.929993,198.410004,191.139999,192.369995,124154600,4.56,2026,7,1,tue,2.37,1
2026-07-08,204.119995,205.149994,195.104996,195.130005,145806099,8.99,2026,7,2,wed,4.61,1

In [97]:
df.index

DatetimeIndex(['2025-07-09', '2025-07-10', '2025-07-11', '2025-07-14',
               '2025-07-15', '2025-07-16', '2025-07-17', '2025-07-18',
               '2025-07-21', '2025-07-22',
               ...
               '2026-06-24', '2026-06-25', '2026-06-26', '2026-06-29',
               '2026-06-30', '2026-07-01', '2026-07-02', '2026-07-06',
               '2026-07-07', '2026-07-08'],
              dtype='datetime64[s]', name='Date', length=251, freq=None)

In [98]:
df.index[5] - df.index[1]

Timedelta('6 days 00:00:00')

In [99]:
df.index[0] + pd.Timedelta(hours=5)

Timestamp('2025-07-09 05:00:00')

In [100]:
df.index[0]

Timestamp('2025-07-09 00:00:00')

In [101]:
pd.Timestamp.now()

Timestamp('2026-07-09 09:53:06.772677')

In [102]:
df.index[0] + pd.DateOffset(months=3, days=5, hours=5, minutes=30, seconds=50)

Timestamp('2025-10-14 05:30:50')

In [103]:
df.index[0]

Timestamp('2025-07-09 00:00:00')

In [104]:
df.index[0]

Timestamp('2025-07-09 00:00:00')

In [105]:
df.index[0] + pd.Timedelta(days=31)

Timestamp('2025-08-09 00:00:00')

In [106]:
df.index[0] + pd.DateOffset(months=1)

Timestamp('2025-08-09 00:00:00')

In [107]:
date = df.index[0:10]
date

DatetimeIndex(['2025-07-09', '2025-07-10', '2025-07-11', '2025-07-14',
               '2025-07-15', '2025-07-16', '2025-07-17', '2025-07-18',
               '2025-07-21', '2025-07-22'],
              dtype='datetime64[s]', name='Date', freq=None)

In [122]:
pd.to_datetime(date)

DatetimeIndex(['2025-07-09', '2025-07-10', '2025-07-11', '2025-07-14',
               '2025-07-15', '2025-07-16', '2025-07-17', '2025-07-18',
               '2025-07-21', '2025-07-22'],
              dtype='datetime64[s]', name='Date', freq=None)

In [113]:
date + pd.Timedelta(days=3)

DatetimeIndex(['2025-07-12', '2025-07-13', '2025-07-14', '2025-07-17',
               '2025-07-18', '2025-07-19', '2025-07-20', '2025-07-21',
               '2025-07-24', '2025-07-25'],
              dtype='datetime64[us]', name='Date', freq=None)

In [123]:
temp = pd.to_datetime([pd.Timestamp.now().date(), (pd.Timestamp.now()+pd.Timedelta(hours=3)).date()])
temp

DatetimeIndex(['2026-07-09', '2026-07-09'], dtype='datetime64[s]', freq=None)

In [139]:
print([pd.Timestamp.now().time(), pd.Timestamp.now().time()])

[datetime.time(10, 11, 13, 344704), datetime.time(10, 11, 13, 344704)]

In [143]:
pd.Timestamp.now().strftime('%Y/%m/%d -> %H|%M|%S')

'2026/07/09 -> 10|24|03'

In [148]:
print(pd.to_datetime(pd.Timestamp.now().strftime('%Y.%m.%d')))

2026-07-09 00:00:00

In [146]:
pd.Timestamp.now().strftime('%H시 %M분 %S초')

'10시 35분 15초'

In [163]:
x = range(0,10)
x

range(0, 10)

In [156]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [176]:
pd.date_range('2022-07-01', periods=10, freq='MS')

DatetimeIndex(['2022-07-01', '2022-08-01', '2022-09-01', '2022-10-01',
               '2022-11-01', '2022-12-01', '2023-01-01', '2023-02-01',
               '2023-03-01', '2023-04-01'],
              dtype='datetime64[us]', freq='MS')

In [178]:
print(pd.Timestamp.now().date())

2026-07-09

In [179]:
print(pd.Timestamp.now().time())

10:46:40.024207

In [180]:
pd.to_datetime('2025-12-25')

Timestamp('2025-12-25 00:00:00')

In [181]:
pd.to_datetime('2025-12-25 18:30:00')

Timestamp('2025-12-25 18:30:00')

In [182]:
pd.date_range('2025-01-01', periods=10)

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
               '2025-01-05', '2025-01-06', '2025-01-07', '2025-01-08',
               '2025-01-09', '2025-01-10'],
              dtype='datetime64[us]', freq='D')

In [185]:
pd.date_range(pd.Timestamp.now().date(), periods=30)

DatetimeIndex(['2026-07-09', '2026-07-10', '2026-07-11', '2026-07-12',
               '2026-07-13', '2026-07-14', '2026-07-15', '2026-07-16',
               '2026-07-17', '2026-07-18', '2026-07-19', '2026-07-20',
               '2026-07-21', '2026-07-22', '2026-07-23', '2026-07-24',
               '2026-07-25', '2026-07-26', '2026-07-27', '2026-07-28',
               '2026-07-29', '2026-07-30', '2026-07-31', '2026-08-01',
               '2026-08-02', '2026-08-03', '2026-08-04', '2026-08-05',
               '2026-08-06', '2026-08-07'],
              dtype='datetime64[s]', freq='D')

In [187]:
pd.date_range(pd.Timestamp.now().date(), periods=20, freq='B')

DatetimeIndex(['2026-07-09', '2026-07-10', '2026-07-13', '2026-07-14',
               '2026-07-15', '2026-07-16', '2026-07-17', '2026-07-20',
               '2026-07-21', '2026-07-22', '2026-07-23', '2026-07-24',
               '2026-07-27', '2026-07-28', '2026-07-29', '2026-07-30',
               '2026-07-31', '2026-08-03', '2026-08-04', '2026-08-05'],
              dtype='datetime64[us]', freq='B')

In [189]:
pd.Timestamp.now() + pd.Timedelta(days=3)

Timestamp('2026-07-12 10:51:52.303892')

In [192]:
pd.Timestamp.now() + pd.Timedelta(weeks=2)

Timestamp('2026-07-23 10:54:04.545711')

In [194]:
pd.to_datetime('2025-07-01') - pd.to_datetime('2025-01-01')

Timedelta('181 days 00:00:00')

In [197]:
pd.Timestamp.now() + pd.Timedelta(days=100)

Timestamp('2026-10-17 10:55:19.001917')

In [198]:
ts = pd.Timestamp("2025-07-09 13:20:30")

In [200]:
ts.year

2025

In [201]:
ts.month

7

In [202]:
ts.day

9

In [208]:
print(ts.date())

2025-07-09

In [209]:
print(ts.time())

13:20:30

In [210]:
ts.hour

13

In [211]:
ts.minute

20

In [212]:
ts.second

30

In [215]:
ts.weekday()

2

In [216]:
ts.day_name()

'Wednesday'

In [217]:
dates = pd.date_range("2025-07-01", periods=10)

In [219]:
dates.year

Index([2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025], dtype='int32')

In [220]:
dates.month

Index([7, 7, 7, 7, 7, 7, 7, 7, 7, 7], dtype='int32')

In [224]:
dates.weekday

Index([1, 2, 3, 4, 5, 6, 0, 1, 2, 3], dtype='int32')

In [227]:
dates.day_name()

Index(['Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday',
       'Monday', 'Tuesday', 'Wednesday', 'Thursday'],
      dtype='str')

In [239]:
dates[dates.weekday >= 5]

DatetimeIndex(['2025-07-05', '2025-07-06'], dtype='datetime64[us]', freq='D')

In [242]:
dates[dates.weekday == 0]

DatetimeIndex(['2025-07-07'], dtype='datetime64[us]', freq='D')

In [247]:
dates[dates >= pd.to_datetime('2025-07-05')]

DatetimeIndex(['2025-07-05', '2025-07-06', '2025-07-07', '2025-07-08',
               '2025-07-09', '2025-07-10'],
              dtype='datetime64[us]', freq='D')

In [250]:
pd.to_datetime("2025-07-09")

Timestamp('2025-07-09 00:00:00')

In [251]:
pd.to_datetime([
"2025-01-01",
"2025-01-03",
"2025-01-05"
])

DatetimeIndex(['2025-01-01', '2025-01-03', '2025-01-05'], dtype='datetime64[us]', freq=None)

In [253]:
pd.Timestamp.now().strftime('%Y/%m/%d')

'2026/07/09'

In [254]:
pd.Timestamp.now().strftime('%Y년 %m월 %d일')

'2026년 07월 09일'

In [3]:
temp = pd.DataFrame({
    "Date": pd.date_range("2025-01-01", periods=20),
    "Sales": range(20)
})

In [4]:
temp

         Date  Sales
0  2025-01-01      0
1  2025-01-02      1
2  2025-01-03      2
3  2025-01-04      3
4  2025-01-05      4
5  2025-01-06      5
6  2025-01-07      6
7  2025-01-08      7
8  2025-01-09      8
9  2025-01-10      9
10 2025-01-11     10
11 2025-01-12     11
12 2025-01-13     12
13 2025-01-14     13
14 2025-01-15     14
15 2025-01-16     15
16 2025-01-17     16
17 2025-01-18     17
18 2025-01-19     18
19 2025-01-20     19

In [5]:
temp['Date'].dtypes

dtype('<M8[us]')

In [6]:
temp.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    20 non-null     datetime64[us]
 1   Sales   20 non-null     int64
dtypes: datetime64[us](1), int64(1)
memory usage: 452.0 bytes

In [12]:
temp.loc[:,"Date"]

0    2025-01-01
1    2025-01-02
2    2025-01-03
3    2025-01-04
4    2025-01-05
5    2025-01-06
6    2025-01-07
7    2025-01-08
8    2025-01-09
9    2025-01-10
10   2025-01-11
11   2025-01-12
12   2025-01-13
13   2025-01-14
14   2025-01-15
15   2025-01-16
16   2025-01-17
17   2025-01-18
18   2025-01-19
19   2025-01-20
Name: Date, dtype: datetime64[us]

In [13]:
type(temp['Date'])

pandas.Series

In [17]:
temp['Year'] = temp['Date'].dt.year
temp.head()

        Date  Sales  Year
0 2025-01-01      0  2025
1 2025-01-02      1  2025
2 2025-01-03      2  2025
3 2025-01-04      3  2025
4 2025-01-05      4  2025

In [18]:
temp['Month'] = temp['Date'].dt.month
temp['Day'] = temp['Date'].dt.day

In [19]:
temp.head()

        Date  Sales  Year  Month  Day
0 2025-01-01      0  2025      1    1
1 2025-01-02      1  2025      1    2
2 2025-01-03      2  2025      1    3
3 2025-01-04      3  2025      1    4
4 2025-01-05      4  2025      1    5

In [32]:
temp['Weekday'] = temp['Date'].dt.weekday

In [36]:
temp['Weekend'] = temp['Weekday'] >= 5

In [69]:
temp['Weekday'] = temp['Date'].dt.day_name().str.slice(0,3)

In [70]:
temp.head()

        Date  Sales  Year  Month  Day Weekday  Weekend
0 2025-01-01      0  2025      1    1     Wed    False
1 2025-01-02      1  2025      1    2     Thu    False
2 2025-01-03      2  2025      1    3     Fri    False
3 2025-01-04      3  2025      1    4     Sat     True
4 2025-01-05      4  2025      1    5     Sun     True

In [73]:
temp[temp['Weekday'] == 'Mon']

         Date  Sales  Year  Month  Day Weekday  Weekend
5  2025-01-06      5  2025      1    6     Mon    False
12 2025-01-13     12  2025      1   13     Mon    False
19 2025-01-20     19  2025      1   20     Mon    False

In [77]:
temp[temp['Date'] >= pd.to_datetime('2025-01-10')]

         Date  Sales  Year  Month  Day Weekday  Weekend
9  2025-01-10      9  2025      1   10     Fri    False
10 2025-01-11     10  2025      1   11     Sat     True
11 2025-01-12     11  2025      1   12     Sun     True
12 2025-01-13     12  2025      1   13     Mon    False
13 2025-01-14     13  2025      1   14     Tue    False
14 2025-01-15     14  2025      1   15     Wed    False
15 2025-01-16     15  2025      1   16     Thu    False
16 2025-01-17     16  2025      1   17     Fri    False
17 2025-01-18     17  2025      1   18     Sat     True
18 2025-01-19     18  2025      1   19     Sun     True
19 2025-01-20     19  2025      1   20     Mon    False

In [81]:
temp.set_index('Date', inplace=True)

In [84]:
temp.loc[temp['Month'] == 1]

            Sales  Year  Month  Day Weekday  Weekend
Date
2025-01-01      0  2025      1    1     Wed    False
2025-01-02      1  2025      1    2     Thu    False
2025-01-03      2  2025      1    3     Fri    False
2025-01-04      3  2025      1    4     Sat     True
2025-01-05      4  2025      1    5     Sun     True
2025-01-06      5  2025      1    6     Mon    False
2025-01-07      6  2025      1    7     Tue    False
2025-01-08      7  2025      1    8     Wed    False
2025-01-09      8  2025      1    9     Thu    False
2025-01-10      9  2025      1   10     Fri    False
2025-01-11     10  2025      1   11     Sat     True
2025-01-12     11  2025      1   12     Sun     True
2025-01-13     12  2025      1   13     Mon    False
2025-01-14     13  2025      1   14     Tue    False
2025-01-15     14  2025      1   15     Wed    False
2025-01-16     15  2025      1   16     Thu    False
2025-01-17     16  2025      1   17     Fri    False
2025-01-18     17  2025      1   18     Sat     True
2025-01-19     18  2025      1   19     Sun     True
2025-01-20     19  2025      1   20     Mon    False

In [86]:
temp.sort_index()

            Sales  Year  Month  Day Weekday  Weekend
Date
2025-01-01      0  2025      1    1     Wed    False
2025-01-02      1  2025      1    2     Thu    False
2025-01-03      2  2025      1    3     Fri    False
2025-01-04      3  2025      1    4     Sat     True
2025-01-05      4  2025      1    5     Sun     True
2025-01-06      5  2025      1    6     Mon    False
2025-01-07      6  2025      1    7     Tue    False
2025-01-08      7  2025      1    8     Wed    False
2025-01-09      8  2025      1    9     Thu    False
2025-01-10      9  2025      1   10     Fri    False
2025-01-11     10  2025      1   11     Sat     True
2025-01-12     11  2025      1   12     Sun     True
2025-01-13     12  2025      1   13     Mon    False
2025-01-14     13  2025      1   14     Tue    False
2025-01-15     14  2025      1   15     Wed    False
2025-01-16     15  2025      1   16     Thu    False
2025-01-17     16  2025      1   17     Fri    False
2025-01-18     17  2025      1   18     Sat     True
2025-01-19     18  2025      1   19     Sun     True
2025-01-20     19  2025      1   20     Mon    False

In [92]:
temp.index + pd.Timedelta(days=1)

DatetimeIndex(['2025-01-02', '2025-01-03', '2025-01-04', '2025-01-05',
               '2025-01-06', '2025-01-07', '2025-01-08', '2025-01-09',
               '2025-01-10', '2025-01-11', '2025-01-12', '2025-01-13',
               '2025-01-14', '2025-01-15', '2025-01-16', '2025-01-17',
               '2025-01-18', '2025-01-19', '2025-01-20', '2025-01-21'],
              dtype='datetime64[us]', name='Date', freq=None)

In [93]:
temp.index + pd.Timedelta(days=7)

DatetimeIndex(['2025-01-08', '2025-01-09', '2025-01-10', '2025-01-11',
               '2025-01-12', '2025-01-13', '2025-01-14', '2025-01-15',
               '2025-01-16', '2025-01-17', '2025-01-18', '2025-01-19',
               '2025-01-20', '2025-01-21', '2025-01-22', '2025-01-23',
               '2025-01-24', '2025-01-25', '2025-01-26', '2025-01-27'],
              dtype='datetime64[us]', name='Date', freq=None)

In [100]:
temp.loc['2025-01-10':'2025-01-15']

            Sales  Year  Month  Day Weekday  Weekend
Date
2025-01-10      9  2025      1   10     Fri    False
2025-01-11     10  2025      1   11     Sat     True
2025-01-12     11  2025      1   12     Sun     True
2025-01-13     12  2025      1   13     Mon    False
2025-01-14     13  2025      1   14     Tue    False
2025-01-15     14  2025      1   15     Wed    False

In [102]:
temp.iloc[0:10]

            Sales  Year  Month  Day Weekday  Weekend
Date
2025-01-01      0  2025      1    1     Wed    False
2025-01-02      1  2025      1    2     Thu    False
2025-01-03      2  2025      1    3     Fri    False
2025-01-04      3  2025      1    4     Sat     True
2025-01-05      4  2025      1    5     Sun     True
2025-01-06      5  2025      1    6     Mon    False
2025-01-07      6  2025      1    7     Tue    False
2025-01-08      7  2025      1    8     Wed    False
2025-01-09      8  2025      1    9     Thu    False
2025-01-10      9  2025      1   10     Fri    False

In [109]:
temp.index.day

Index([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], dtype='int32', name='Date')

In [110]:
rng = np.random.default_rng()

In [112]:
rng.integers(100,500,100)

array([479, 237, 206, 380, 391, 155, 115, 238, 180, 136, 424, 314, 165,
       185, 126, 375, 480, 214, 262, 145, 123, 400, 449, 256, 132, 378,
       270, 232, 225, 164, 231, 283, 334, 141, 176, 196, 480, 369, 361,
       400, 193, 253, 408, 154, 186, 166, 315, 240, 316, 342, 157, 383,
       239, 347, 100, 269, 404, 481, 274, 398, 258, 165, 355, 370, 159,
       461, 238, 269, 159, 172, 248, 133, 347, 395, 472, 362, 235, 146,
       263, 135, 414, 462, 180, 398, 107, 331, 129, 247, 449, 352, 238,
       338, 371, 464, 443, 219, 492, 477, 457, 339])

In [114]:
np.random.randint(100,500,100)

array([410, 484, 184, 156, 146, 433, 131, 366, 442, 328, 185, 125, 149,
       253, 336, 107, 150, 378, 418, 338, 124, 161, 306, 279, 156, 320,
       154, 289, 389, 273, 398, 199, 160, 327, 246, 364, 156, 190, 371,
       401, 276, 489, 166, 464, 292, 485, 153, 459, 114, 255, 302, 197,
       485, 341, 143, 471, 291, 402, 155, 452, 320, 212, 275, 236, 491,
       450, 261, 271, 488, 285, 202, 351, 390, 229, 446, 119, 170, 279,
       478, 454, 325, 489, 260, 127, 105, 211, 385, 106, 287, 133, 192,
       232, 102, 399, 405, 465, 189, 340, 153, 239], dtype=int32)

In [113]:
df = pd.DataFrame({'Date':pd.date_range('2025-01-01', periods=100), 'Sales':rng.integers(100,500,100)})

In [116]:
df.head()

        Date  Sales
0 2025-01-01    330
1 2025-01-02    377
2 2025-01-03    444
3 2025-01-04    202
4 2025-01-05    288

In [117]:
df.set_index('Date', inplace=True)

In [119]:
df.head()

            Sales
Date
2025-01-01    330
2025-01-02    377
2025-01-03    444
2025-01-04    202
2025-01-05    288

In [123]:
df.resample('MS').sum()

            Sales
Date
2025-01-01   9736
2025-02-01   8138
2025-03-01   9209
2025-04-01   3052

In [126]:
df.resample('ME').sum()

            Sales
Date
2025-01-31   9736
2025-02-28   8138
2025-03-31   9209
2025-04-30   3052

In [127]:
df.resample('ME').mean()

                 Sales
Date
2025-01-31  314.064516
2025-02-28  290.642857
2025-03-31  297.064516
2025-04-30  305.200000

In [128]:
df.resample('ME').max()

            Sales
Date
2025-01-31    499
2025-02-28    494
2025-03-31    487
2025-04-30    464

In [132]:
df.resample('YE').sum()

            Sales
Date
2025-12-31  30135

In [133]:
df.head()

            Sales
Date
2025-01-01    330
2025-01-02    377
2025-01-03    444
2025-01-04    202
2025-01-05    288

In [137]:
df.groupby(df.index.day_name())['Sales'].sum()

Date
Friday       4554
Monday       3299
Saturday     4548
Sunday       4931
Thursday     4266
Tuesday      4251
Wednesday    4286
Name: Sales, dtype: int64

In [138]:
df.resample('ME').mean()

                 Sales
Date
2025-01-31  314.064516
2025-02-28  290.642857
2025-03-31  297.064516
2025-04-30  305.200000

In [144]:
df.head()

            Sales
Date
2025-01-01    330
2025-01-02    377
2025-01-03    444
2025-01-04    202
2025-01-05    288

In [149]:
df['Sales_MA3'] = df.rolling(3).mean()

In [150]:
df.head()

            Sales   Sales_MA3
Date
2025-01-01    330         NaN
2025-01-02    377         NaN
2025-01-03    444  383.666667
2025-01-04    202  341.000000
2025-01-05    288  311.333333

In [156]:
df['Sales_MA7'] = df['Sales'].rolling(7).mean()
df['Sales_MA30'] = df['Sales'].rolling(30).mean()

In [158]:
df.head(30)

            Sales   Sales_MA3   Sales_MA7  Sales_MA30
Date
2025-01-01    330         NaN         NaN         NaN
2025-01-02    377         NaN         NaN         NaN
2025-01-03    444  383.666667         NaN         NaN
2025-01-04    202  341.000000         NaN         NaN
2025-01-05    288  311.333333         NaN         NaN
2025-01-06    129  206.333333         NaN         NaN
2025-01-07    499  305.333333  324.142857         NaN
2025-01-08    481  369.666667  345.714286         NaN
2025-01-09    257  412.333333  328.571429         NaN
2025-01-10    477  405.000000  333.285714         NaN
2025-01-11    278  337.333333  344.142857         NaN
2025-01-12    225  326.666667  335.142857         NaN
2025-01-13    253  252.000000  352.857143         NaN
2025-01-14    329  269.000000  328.571429         NaN
2025-01-15    422  334.666667  320.142857         NaN
2025-01-16    288  346.333333  324.571429         NaN
2025-01-17    387  365.666667  311.714286         NaN
2025-01-18    461  378.666667  337.857143         NaN
2025-01-19    475  441.000000  373.571429         NaN
2025-01-20    116  350.666667  354.000000         NaN
2025-01-21    280  290.333333  347.000000         NaN
2025-01-22    201  199.000000  315.428571         NaN
2025-01-23    332  271.000000  321.714286         NaN
2025-01-24    396  309.666667  323.000000         NaN
2025-01-25    197  308.333333  285.285714         NaN
2025-01-26    371  321.333333  270.428571         NaN
2025-01-27    305  291.000000  297.428571         NaN
2025-01-28    268  314.666667  295.714286         NaN
2025-01-29    291  288.000000  308.571429         NaN
2025-01-30    259  272.666667  298.142857       320.6

In [162]:
df.drop(columns=['Sales_MA3', 'Sales_MA7', 'Sales_MA30'], inplace=True)

In [166]:
df['Sales_before'] = df['Sales'].shift()

In [170]:
df.head()

            Sales  Sales_before
Date
2025-01-01    330           NaN
2025-01-02    377         330.0
2025-01-03    444         377.0
2025-01-04    202         444.0
2025-01-05    288         202.0

In [174]:
df['diff'] = df['Sales'] - df['Sales_before']

In [173]:
df['Sales'] - df['Sales'].shift()

Date
2025-01-01      NaN
2025-01-02     47.0
2025-01-03     67.0
2025-01-04   -242.0
2025-01-05     86.0
              ...
2025-04-06     22.0
2025-04-07    146.0
2025-04-08   -352.0
2025-04-09    284.0
2025-04-10    -28.0
Name: Sales, Length: 100, dtype: float64

In [175]:
df.head()

            Sales  Sales_before   diff
Date
2025-01-01    330           NaN    NaN
2025-01-02    377         330.0   47.0
2025-01-03    444         377.0   67.0
2025-01-04    202         444.0 -242.0
2025-01-05    288         202.0   86.0

In [176]:
(377-330)/330

0.14242424242424243

In [178]:
(444-377)/377

0.17771883289124668

In [179]:
(202-444)/444

-0.545045045045045

In [177]:
df['Sales'].pct_change()

Date
2025-01-01         NaN
2025-01-02    0.142424
2025-01-03    0.177719
2025-01-04   -0.545045
2025-01-05    0.425743
                ...
2025-04-06    0.074324
2025-04-07    0.459119
2025-04-08   -0.758621
2025-04-09    2.535714
2025-04-10   -0.070707
Name: Sales, Length: 100, dtype: float64

In [181]:
df.head()

            Sales  Sales_before   diff
Date
2025-01-01    330           NaN    NaN
2025-01-02    377         330.0   47.0
2025-01-03    444         377.0   67.0
2025-01-04    202         444.0 -242.0
2025-01-05    288         202.0   86.0

In [182]:
df['growth'] = (df['Sales']-df['Sales_before'])/df['Sales_before']

In [183]:
df.head()

            Sales  Sales_before   diff    growth
Date
2025-01-01    330           NaN    NaN       NaN
2025-01-02    377         330.0   47.0  0.142424
2025-01-03    444         377.0   67.0  0.177719
2025-01-04    202         444.0 -242.0 -0.545045
2025-01-05    288         202.0   86.0  0.425743

In [184]:
df['Sales'].pct_change()

Date
2025-01-01         NaN
2025-01-02    0.142424
2025-01-03    0.177719
2025-01-04   -0.545045
2025-01-05    0.425743
                ...
2025-04-06    0.074324
2025-04-07    0.459119
2025-04-08   -0.758621
2025-04-09    2.535714
2025-04-10   -0.070707
Name: Sales, Length: 100, dtype: float64

In [ ]:
df['Sales'].resample('ME').mean()

Date
2025-01-31    9736
2025-02-28    8138
2025-03-31    9209
2025-04-30    3052
Freq: ME, Name: Sales, dtype: int64

In [ ]:
df['Sales'].resample('ME').mean().pct_change()

Date
2025-01-31         NaN
2025-02-28   -0.074576
2025-03-31    0.022095
2025-04-30    0.027386
Freq: ME, Name: Sales, dtype: float64

In [193]:
df['Sales'].resample('ME').sum()

Date
2025-01-31    9736
2025-02-28    8138
2025-03-31    9209
2025-04-30    3052
Freq: ME, Name: Sales, dtype: int64

In [194]:
df['Sales'].resample('ME').sum().pct_change()

Date
2025-01-31         NaN
2025-02-28   -0.164133
2025-03-31    0.131605
2025-04-30   -0.668585
Freq: ME, Name: Sales, dtype: float64