In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import yfinance as yf

In [57]:
# raw = yf.download("AAPL", start="2026-01-01", end="2026-06-30")
raw = yf.download("NVDA", period="1y", interval="1d", multi_level_index=False)

[*********************100%***********************]  1 of 1 completed

In [58]:
raw.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 251 entries, 2025-07-08 to 2026-07-07
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Close   251 non-null    float64
 1   High    251 non-null    float64
 2   Low     251 non-null    float64
 3   Open    251 non-null    float64
 4   Volume  251 non-null    int64
dtypes: float64(4), int64(1)
memory usage: 11.8 KB

In [59]:
raw.isna().sum()

Close     0
High      0
Low       0
Open      0
Volume    0
dtype: int64

In [60]:
raw.tail()

                 Close        High         Low        Open     Volume
Date
2026-06-30  200.089996  200.630005  195.110001  197.240005  166476700
2026-07-01  197.580002  199.850006  193.449997  196.199997  146147600
2026-07-02  194.830002  200.059998  192.350006  197.139999  142068700
2026-07-06  195.550003  197.550003  193.990005  194.419998  108999000
2026-07-07  196.929993  198.410004  191.149994  192.369995  122966441

In [61]:
df = raw.copy()

In [62]:
df.describe()

            Close        High         Low        Open        Volume
count  251.000000  251.000000  251.000000  251.000000  2.510000e+02
mean   187.892170  190.564074  185.160439  188.044908  1.741535e+08
std     14.018680   14.570181   13.677191   14.157265  4.564198e+07
min    159.973419  160.193384  158.363686  159.303532  6.552850e+07
25%    178.200409  180.585207  175.774994  178.115420  1.438414e+08
50%    184.849991  187.139866  182.000149  184.739995  1.664767e+08
75%    195.368996  197.608803  191.583969  195.113578  1.916750e+08
max    235.740005  236.539993  229.300003  229.869995  3.608079e+08

In [71]:
df.shape

(251, 5)

In [72]:
df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 251 entries, 2025-07-08 to 2026-07-07
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Close   251 non-null    float64
 1   High    251 non-null    float64
 2   Low     251 non-null    float64
 3   Open    251 non-null    float64
 4   Volume  251 non-null    int64
dtypes: float64(4), int64(1)
memory usage: 11.8 KB

In [73]:
df.head()

                 Close        High         Low        Open     Volume
Date
2025-07-08  159.973419  160.193384  158.363686  159.303532  138133000
2025-07-09  162.852936  164.392673  161.133220  161.193208  183656400
2025-07-10  164.072739  164.472666  161.583147  164.292703  167704100
2025-07-11  164.892593  167.862101  163.442837  163.692796  193633300
2025-07-14  164.042740  165.462502  161.993078  165.342512  136975800

In [74]:
df.tail()

                 Close        High         Low        Open     Volume
Date
2026-06-30  200.089996  200.630005  195.110001  197.240005  166476700
2026-07-01  197.580002  199.850006  193.449997  196.199997  146147600
2026-07-02  194.830002  200.059998  192.350006  197.139999  142068700
2026-07-06  195.550003  197.550003  193.990005  194.419998  108999000
2026-07-07  196.929993  198.410004  191.149994  192.369995  122966441

In [92]:
df['Close'].agg(['max', 'min', 'mean']).map('{:.0f}'.format)

max     236
min     160
mean    188
Name: Close, dtype: str

In [94]:
df['Volume'].agg(['mean', 'median', 'std']).map('{:,.0f}'.format)

mean      174,153,503
median    166,476,700
std        45,641,983
Name: Volume, dtype: str

In [89]:
df['Volume'].agg(['mean', 'median', 'std']).map('{:,.03f}'.format)

mean      174,153,503.351
median    166,476,700.000
std        45,641,982.690
Name: Volume, dtype: str

In [102]:
print(f"{((df['High'] - df['Low']).mean()):.0f}")

5

In [127]:
new = df[['Close', 'Volume']]

In [128]:
new

                 Close     Volume
Date
2025-07-08  159.973419  138133000
2025-07-09  162.852936  183656400
2025-07-10  164.072739  167704100
2025-07-11  164.892593  193633300
2025-07-14  164.042740  136975800
...                ...        ...
2026-06-30  200.089996  166476700
2026-07-01  197.580002  146147600
2026-07-02  194.830002  142068700
2026-07-06  195.550003  108999000
2026-07-07  196.929993  122966441

[251 rows x 2 columns]

In [129]:
df.tail(10)

                 Close        High         Low        Open     Volume
Date
2026-06-23  200.039993  203.770004  200.000000  202.169998  153496200
2026-06-24  199.000000  201.669998  196.580002  200.119995  151810700
2026-06-25  195.740005  200.800003  192.130005  200.080002  149550000
2026-06-26  192.529999  195.550003  191.220001  193.119995  179304100
2026-06-29  194.970001  196.179993  189.800003  193.850006  148835700
2026-06-30  200.089996  200.630005  195.110001  197.240005  166476700
2026-07-01  197.580002  199.850006  193.449997  196.199997  146147600
2026-07-02  194.830002  200.059998  192.350006  197.139999  142068700
2026-07-06  195.550003  197.550003  193.990005  194.419998  108999000
2026-07-07  196.929993  198.410004  191.149994  192.369995  122966441

In [132]:
df.iloc[-10:]

                 Close        High         Low        Open     Volume
Date
2026-06-23  200.039993  203.770004  200.000000  202.169998  153496200
2026-06-24  199.000000  201.669998  196.580002  200.119995  151810700
2026-06-25  195.740005  200.800003  192.130005  200.080002  149550000
2026-06-26  192.529999  195.550003  191.220001  193.119995  179304100
2026-06-29  194.970001  196.179993  189.800003  193.850006  148835700
2026-06-30  200.089996  200.630005  195.110001  197.240005  166476700
2026-07-01  197.580002  199.850006  193.449997  196.199997  146147600
2026-07-02  194.830002  200.059998  192.350006  197.139999  142068700
2026-07-06  195.550003  197.550003  193.990005  194.419998  108999000
2026-07-07  196.929993  198.410004  191.149994  192.369995  122966441

In [141]:
new.loc[new['Close'] > new['Close'].quantile(0.9), 'Close'].index

DatetimeIndex(['2026-04-27', '2026-04-28', '2026-04-29', '2026-05-07',
               '2026-05-08', '2026-05-11', '2026-05-12', '2026-05-13',
               '2026-05-14', '2026-05-15', '2026-05-18', '2026-05-19',
               '2026-05-20', '2026-05-21', '2026-05-22', '2026-05-26',
               '2026-05-27', '2026-05-28', '2026-05-29', '2026-06-01',
               '2026-06-02', '2026-06-03', '2026-06-04', '2026-06-15',
               '2026-06-18'],
              dtype='datetime64[s]', name='Date', freq=None)

In [142]:
len(new.loc[new['Close'] > new['Close'].quantile(0.9), 'Close'].index)

25

In [157]:
print(f"종가 {new['Close'].quantile(0.9):.2f} 이상인 날: {len(new.loc[new['Close'] > new['Close'].quantile(0.9), 'Close'])}일")

종가 208.65 이상인 날: 25일

In [145]:
new.loc[new['Volume'] > new['Volume'].mean()]

                 Close     Volume
Date
2025-07-09  162.852936  183656400
2025-07-11  164.892593  193633300
2025-07-15  170.671631  230627400
2025-07-22  167.002258  193114300
2025-07-30  179.240219  174312200
...                ...        ...
2026-06-02  222.820007  193362900
2026-06-05  205.100006  219655500
2026-06-09  208.190002  180962500
2026-06-18  210.690002  241272000
2026-06-26  192.529999  179304100

[108 rows x 2 columns]

In [148]:
new.sort_values('Volume', ascending=False)

                 Close     Volume
Date
2026-02-26  184.879990  360807900
2025-11-21  178.860367  346926200
2025-11-20  180.620163  343504800
2025-12-19  180.980209  324925900
2025-11-25  177.800476  320600300
...                ...        ...
2026-04-21  199.880005  107945300
2026-04-06  177.639999  107564300
2026-04-22  202.500000  107501000
2025-12-30  187.529846   97687300
2025-12-24  188.599792   65528500

[251 rows x 2 columns]

In [232]:
df['Daily_Change'] = (df['Close'] - df['Open']).round(3)

In [233]:
df[['Open', 'Close', 'Daily_Change']].head()

                  Open       Close  Daily_Change
Date
2025-07-08  159.303532  159.973419          0.67
2025-07-09  161.193208  162.852936          1.66
2025-07-10  164.292703  164.072739         -0.22
2025-07-11  163.692796  164.892593          1.20
2025-07-14  165.342512  164.042740         -1.30

In [166]:
new.drop(columns='Daily_Change', inplace=True)

In [167]:
new

                 Close     Volume
Date
2025-07-08  159.973419  138133000
2025-07-09  162.852936  183656400
2025-07-10  164.072739  167704100
2025-07-11  164.892593  193633300
2025-07-14  164.042740  136975800
...                ...        ...
2026-06-30  200.089996  166476700
2026-07-01  197.580002  146147600
2026-07-02  194.830002  142068700
2026-07-06  195.550003  108999000
2026-07-07  196.929993  122966441

[251 rows x 2 columns]

In [234]:
df['Change_Rate'] = ((df['Close'] - df['Open'])/df['Open']*100).round(3)

In [231]:
df

,Close,High,Low,Open,Volume,Daily_Change,Change_Rate,Year,Month,Weekday
Date,,,,,,,,,,
2025-07-08,159.973419,160.193384,158.363686,159.303532,138133000,0.669887,0.421,2025,7,tue
2025-07-09,162.852936,164.392673,161.133220,161.193208,183656400,1.659728,1.030,2025,7,wed
2025-07-10,164.072739,164.472666,161.583147,164.292703,167704100,-0.219965,-0.134,2025,7,thu
2025-07-11,164.892593,167.862101,163.442837,163.692796,193633300,1.199798,0.733,2025,7,fri
2025-07-14,164.042740,165.462502,161.993078,165.342512,136975800,-1.299772,-0.786,2025,7,mon
...,...,...,...,...,...,...,...,...,...,...
2026-06-30,200.089996,200.630005,195.110001,197.240005,166476700,2.849991,1.445,2026,6,tue
2026-07-01,197.580002,199.850006,193.449997,196.199997,146147600,1.380005,0.703,2026,7,wed
2026-07-02,194.830002,200.059998,192.350006,197.139999,142068700,-2.309998,-1.172,2026,7,thu
2026-07-06,195.550003,197.550003,193.990005,194.419998,108999000,1.130005,0.581,2026,7,mon
2026-07-07,196.929993,198.410004,191.149994,192.369995,122966441,4.559998,2.370,2026,7,tue

In [235]:
df.index.day_name()

Index(['Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Monday', 'Tuesday',
       'Wednesday', 'Thursday', 'Friday', 'Monday',
       ...
       'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Monday', 'Tuesday',
       'Wednesday', 'Thursday', 'Monday', 'Tuesday'],
      dtype='str', name='Date', length=251)

In [237]:
df.index.weekday

Index([1, 2, 3, 4, 0, 1, 2, 3, 4, 0,
       ...
       1, 2, 3, 4, 0, 1, 2, 3, 0, 1],
      dtype='int32', name='Date', length=251)

In [186]:
df['Year'] = df.index.year

In [188]:
df['Month'] = df.index.month

In [190]:
df['Weekday'] = df.index.weekday

In [191]:
df

,Close,High,Low,Open,Volume,Daily_Change,Change_Rate,Year,Month,Weekday
Date,,,,,,,,,,
2025-07-08,159.973419,160.193384,158.363686,159.303532,138133000,0.669887,0.420510,2025,7,1
2025-07-09,162.852936,164.392673,161.133220,161.193208,183656400,1.659728,1.029651,2025,7,2
2025-07-10,164.072739,164.472666,161.583147,164.292703,167704100,-0.219965,-0.133886,2025,7,3
2025-07-11,164.892593,167.862101,163.442837,163.692796,193633300,1.199798,0.732957,2025,7,4
2025-07-14,164.042740,165.462502,161.993078,165.342512,136975800,-1.299772,-0.786109,2025,7,0
...,...,...,...,...,...,...,...,...,...,...
2026-06-30,200.089996,200.630005,195.110001,197.240005,166476700,2.849991,1.444935,2026,6,1
2026-07-01,197.580002,199.850006,193.449997,196.199997,146147600,1.380005,0.703366,2026,7,2
2026-07-02,194.830002,200.059998,192.350006,197.139999,142068700,-2.309998,-1.171755,2026,7,3
2026-07-06,195.550003,197.550003,193.990005,194.419998,108999000,1.130005,0.581218,2026,7,0
2026-07-07,196.929993,198.410004,191.149994,192.369995,122966441,4.559998,2.370431,2026,7,1

In [205]:
temp = ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']

In [206]:
temp

['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']

In [207]:
dict = {num:item for num, item in enumerate(temp)}

In [208]:
dict

{0: 'mon', 1: 'tue', 2: 'wed', 3: 'thu', 4: 'fri', 5: 'sat', 6: 'sun'}

In [209]:
df['Weekday'].unique()

array([1, 2, 3, 4, 0], dtype=int32)

In [212]:
df['Weekday'] = df['Weekday'].map(dict)

In [213]:
df

,Close,High,Low,Open,Volume,Daily_Change,Change_Rate,Year,Month,Weekday
Date,,,,,,,,,,
2025-07-08,159.973419,160.193384,158.363686,159.303532,138133000,0.669887,0.420510,2025,7,tue
2025-07-09,162.852936,164.392673,161.133220,161.193208,183656400,1.659728,1.029651,2025,7,wed
2025-07-10,164.072739,164.472666,161.583147,164.292703,167704100,-0.219965,-0.133886,2025,7,thu
2025-07-11,164.892593,167.862101,163.442837,163.692796,193633300,1.199798,0.732957,2025,7,fri
2025-07-14,164.042740,165.462502,161.993078,165.342512,136975800,-1.299772,-0.786109,2025,7,mon
...,...,...,...,...,...,...,...,...,...,...
2026-06-30,200.089996,200.630005,195.110001,197.240005,166476700,2.849991,1.444935,2026,6,tue
2026-07-01,197.580002,199.850006,193.449997,196.199997,146147600,1.380005,0.703366,2026,7,wed
2026-07-02,194.830002,200.059998,192.350006,197.139999,142068700,-2.309998,-1.171755,2026,7,thu
2026-07-06,195.550003,197.550003,193.990005,194.419998,108999000,1.130005,0.581218,2026,7,mon
2026-07-07,196.929993,198.410004,191.149994,192.369995,122966441,4.559998,2.370431,2026,7,tue

In [239]:
df.groupby('Month')[['Close', 'Volume']].agg({'Close':'mean', 'Volume':'sum'})

            Close      Volume
Month
1      186.711894  3292228600
2      185.701528  3745445000
3      178.552773  4027150800
4      195.198572  3129548700
5      215.458001  3324840700
6      206.629524  3424306300
7      175.166366  3448763341
8      179.384468  3608891200
9      175.721304  3890495300
10     188.232375  4031017400
11     187.962520  4160148300
12     182.324673  3629693700

In [240]:
df.groupby('Month').agg({'Close':'mean', 'Volume':'sum'})

            Close      Volume
Month
1      186.711894  3292228600
2      185.701528  3745445000
3      178.552773  4027150800
4      195.198572  3129548700
5      215.458001  3324840700
6      206.629524  3424306300
7      175.166366  3448763341
8      179.384468  3608891200
9      175.721304  3890495300
10     188.232375  4031017400
11     187.962520  4160148300
12     182.324673  3629693700

In [220]:
df.groupby('Year')['Close'].agg(['max', 'min'])

             max         min
Year
2025  207.017273  159.973419
2026  235.740005  165.169998

In [241]:
df.groupby('Year').agg({'High':'max', 'Low':'min'})

            High         Low
Year
2025  212.166717  158.363686
2026  236.539993  164.270004

In [229]:
df[df['Change_Rate'] > 0]['Change_Rate']

Date
2025-07-08    0.420510
2025-07-09    1.029651
2025-07-11    0.732957
2025-07-16    0.181222
2025-07-17    0.569699
                ...
2026-06-29    0.577764
2026-06-30    1.444935
2026-07-01    0.703366
2026-07-06    0.581218
2026-07-07    2.370431
Name: Change_Rate, Length: 128, dtype: float64

In [245]:
df['Price_up'] = (df['Close'] > df['Open']).astype(int)

In [246]:
df

,Close,High,Low,Open,Volume,Daily_Change,Change_Rate,Year,Month,Weekday,Price_up
Date,,,,,,,,,,,
2025-07-08,159.973419,160.193384,158.363686,159.303532,138133000,0.67,0.421,2025,7,tue,1
2025-07-09,162.852936,164.392673,161.133220,161.193208,183656400,1.66,1.030,2025,7,wed,1
2025-07-10,164.072739,164.472666,161.583147,164.292703,167704100,-0.22,-0.134,2025,7,thu,0
2025-07-11,164.892593,167.862101,163.442837,163.692796,193633300,1.20,0.733,2025,7,fri,1
2025-07-14,164.042740,165.462502,161.993078,165.342512,136975800,-1.30,-0.786,2025,7,mon,0
...,...,...,...,...,...,...,...,...,...,...,...
2026-06-30,200.089996,200.630005,195.110001,197.240005,166476700,2.85,1.445,2026,6,tue,1
2026-07-01,197.580002,199.850006,193.449997,196.199997,146147600,1.38,0.703,2026,7,wed,1
2026-07-02,194.830002,200.059998,192.350006,197.139999,142068700,-2.31,-1.172,2026,7,thu,0
2026-07-06,195.550003,197.550003,193.990005,194.419998,108999000,1.13,0.581,2026,7,mon,1
2026-07-07,196.929993,198.410004,191.149994,192.369995,122966441,4.56,2.370,2026,7,tue,1

In [269]:
pd.concat([df['Price_up'].head(10), df['Price_up'].shift().head(10)], axis=1)

            Price_up  Price_up
Date
2025-07-08         1       NaN
2025-07-09         1       1.0
2025-07-10         0       1.0
2025-07-11         1       0.0
2025-07-14         0       1.0
2025-07-15         0       0.0
2025-07-16         1       0.0
2025-07-17         1       1.0
2025-07-18         0       1.0
2025-07-21         0       0.0

In [273]:
df['Price_up'].groupby(df['Price_up'] != df['Price_up'].shift()).cumsum()

Date
2025-07-08     1
2025-07-09     1
2025-07-10     1
2025-07-11     2
2025-07-14     2
              ..
2026-06-30    65
2026-07-01    66
2026-07-02    60
2026-07-06    61
2026-07-07    67
Name: Price_up, Length: 251, dtype: int64

In [299]:
temp = ''.join(df['Price_up'].values.astype(str))
temp

'11010011000110101001010111010101111100010101110110011100111110010110100010001111000000011000110100110010010100100100101111000001001101001110111000001100001011111001111011100100100110001011101111111101011100000111111100110000101001000011100100000111011'

In [308]:
x = temp.split('0')
x

['11',
 '1',
 '',
 '11',
 '',
 '',
 '11',
 '1',
 '1',
 '',
 '1',
 '1',
 '111',
 '1',
 '1',
 '11111',
 '',
 '',
 '1',
 '1',
 '111',
 '11',
 '',
 '111',
 '',
 '11111',
 '',
 '1',
 '11',
 '1',
 '',
 '',
 '1',
 '',
 '',
 '1111',
 '',
 '',
 '',
 '',
 '',
 '',
 '11',
 '',
 '',
 '11',
 '1',
 '',
 '11',
 '',
 '1',
 '',
 '1',
 '1',
 '',
 '1',
 '',
 '1',
 '',
 '1',
 '1111',
 '',
 '',
 '',
 '',
 '1',
 '',
 '11',
 '1',
 '',
 '111',
 '111',
 '',
 '',
 '',
 '',
 '11',
 '',
 '',
 '',
 '1',
 '11111',
 '',
 '1111',
 '111',
 '',
 '1',
 '',
 '1',
 '',
 '11',
 '',
 '',
 '1',
 '111',
 '11111111',
 '1',
 '111',
 '',
 '',
 '',
 '',
 '1111111',
 '',
 '11',
 '',
 '',
 '',
 '1',
 '1',
 '',
 '1',
 '',
 '',
 '',
 '111',
 '',
 '1',
 '',
 '',
 '',
 '',
 '111',
 '11']

In [310]:
length = 0

for i in x:
    if len(i) > length:
        length = len(i)

print('Max: ', length)

Max:  8

In [336]:
x = df['Price_up'].values
x

array([1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1])

In [318]:

num = 0
max = 0
max_idx = []

for idx, i in enumerate(x):
    if i == 1:
        num += 1
        if num > max:
            max = num
            max_idx.append(idx)
    else:
        num = 0

In [319]:
max

8

In [320]:
max_idx

[0, 1, 25, 34, 35, 195, 196, 197]

In [338]:
x[190:198]

array([1, 1, 1, 1, 1, 1, 1, 1])

In [333]:
arr = df['Price_up'].values

In [334]:
max_len = 0       # 가장 긴 길이
max_start = -1    # 가장 긴 구간의 시작 인덱스

current_len = 0
current_start = 0

for i, x in enumerate(arr):
    if x == 1:
        if current_len == 0:
            current_start = i      # 새로운 연속 구간 시작
        current_len += 1

        if current_len > max_len:
            max_len = current_len
            max_start = current_start
    else:
        current_len = 0

print(f'최대 연속 개수 : {max_len}')
print(f'시작 인덱스   : {max_start}')
print(f'끝 인덱스     : {max_start + max_len - 1}')

최대 연속 개수 : 8
시작 인덱스   : 190
끝 인덱스     : 197

In [339]:
df

,Close,High,Low,Open,Volume,Daily_Change,Change_Rate,Year,Month,Weekday,Price_up
Date,,,,,,,,,,,
2025-07-08,159.973419,160.193384,158.363686,159.303532,138133000,0.67,0.421,2025,7,tue,1
2025-07-09,162.852936,164.392673,161.133220,161.193208,183656400,1.66,1.030,2025,7,wed,1
2025-07-10,164.072739,164.472666,161.583147,164.292703,167704100,-0.22,-0.134,2025,7,thu,0
2025-07-11,164.892593,167.862101,163.442837,163.692796,193633300,1.20,0.733,2025,7,fri,1
2025-07-14,164.042740,165.462502,161.993078,165.342512,136975800,-1.30,-0.786,2025,7,mon,0
...,...,...,...,...,...,...,...,...,...,...,...
2026-06-30,200.089996,200.630005,195.110001,197.240005,166476700,2.85,1.445,2026,6,tue,1
2026-07-01,197.580002,199.850006,193.449997,196.199997,146147600,1.38,0.703,2026,7,wed,1
2026-07-02,194.830002,200.059998,192.350006,197.139999,142068700,-2.31,-1.172,2026,7,thu,0
2026-07-06,195.550003,197.550003,193.990005,194.419998,108999000,1.13,0.581,2026,7,mon,1
2026-07-07,196.929993,198.410004,191.149994,192.369995,122966441,4.56,2.370,2026,7,tue,1

In [340]:
df.index

DatetimeIndex(['2025-07-08', '2025-07-09', '2025-07-10', '2025-07-11',
               '2025-07-14', '2025-07-15', '2025-07-16', '2025-07-17',
               '2025-07-18', '2025-07-21',
               ...
               '2026-06-23', '2026-06-24', '2026-06-25', '2026-06-26',
               '2026-06-29', '2026-06-30', '2026-07-01', '2026-07-02',
               '2026-07-06', '2026-07-07'],
              dtype='datetime64[s]', name='Date', length=251, freq=None)

In [344]:
df.index[5] - df.index[1]

Timedelta('6 days 00:00:00')

In [354]:
df.index[0] + pd.Timedelta(hours=5)

Timestamp('2025-07-08 05:00:00')

In [352]:
df.index[0]

Timestamp('2025-07-08 00:00:00')

In [355]:
pd.Timestamp.now()

Timestamp('2026-07-08 16:25:14.780637')

In [365]:
df.index[0] + pd.DateOffset(months=3, days=5, hours=5, minutes=30, seconds=50)

Timestamp('2025-10-13 05:30:50')

In [366]:
df.index[0]

Timestamp('2025-07-08 00:00:00')

In [367]:
df.index[0]

Timestamp('2025-07-08 00:00:00')

In [378]:
df.index[0] + pd.Timedelta(days=31)

Timestamp('2025-08-08 00:00:00')

In [369]:
df.index[0] + pd.DateOffset(months=1)

Timestamp('2025-08-08 00:00:00')

In [379]:
date = df.index[0:10]
date

DatetimeIndex(['2025-07-08', '2025-07-09', '2025-07-10', '2025-07-11',
               '2025-07-14', '2025-07-15', '2025-07-16', '2025-07-17',
               '2025-07-18', '2025-07-21'],
              dtype='datetime64[s]', name='Date', freq=None)

In [382]:
pd.to_datetime(date)

DatetimeIndex(['2025-07-08', '2025-07-09', '2025-07-10', '2025-07-11',
               '2025-07-14', '2025-07-15', '2025-07-16', '2025-07-17',
               '2025-07-18', '2025-07-21'],
              dtype='datetime64[s]', name='Date', freq=None)