In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
sales_data = pd.DataFrame({
    'product': ['노트북', '마우스', '키보드', '모니터', '스피커'],
    'price': [1200000, 25000, 80000, 350000, 120000],
    'quantity': [10, 50, 30, 15, 25],
    'category': ['전자제품', '주변기기', '주변기기', '전자제품', '주변기기']
})

In [4]:
sales_data.groupby('category').get_group('전자제품')

  product    price  quantity category
0     노트북  1200000        10     전자제품
3     모니터   350000        15     전자제품

In [6]:
sales_data.groupby('category')['price'].transform('mean')

0    775000.0
1     75000.0
2     75000.0
3    775000.0
4     75000.0
Name: price, dtype: float64

In [18]:
dates = pd.date_range('2024-01-01', periods=5, freq='D')
data = pd.DataFrame({
    'date':dates,
    'sales': [100, 150, 200, 120, 180],
    'returns': [5, 8, 12, 6, 9]
})

In [23]:
data.set_index('date', inplace=True)

In [24]:
data

            sales  returns
date
2024-01-01    100        5
2024-01-02    150        8
2024-01-03    200       12
2024-01-04    120        6
2024-01-05    180        9

In [33]:
data[data.index.year == 2024]

            sales  returns
date
2024-01-01    100        5
2024-01-02    150        8
2024-01-03    200       12
2024-01-04    120        6
2024-01-05    180        9

In [35]:
data = pd.DataFrame({
    'product': ['노트북', '마우스', '키보드', '모니터', '스피커'],
    'price': [1200000, 25000, 80000, 350000, 120000],
    'quantity': [10, 50, 30, 15, 25],
    'cost': [800000, 15000, 50000, 200000, 80000]
})

In [36]:
data

  product    price  quantity    cost
0     노트북  1200000        10  800000
1     마우스    25000        50   15000
2     키보드    80000        30   50000
3     모니터   350000        15  200000
4     스피커   120000        25   80000

In [39]:
data['total_sales'] = data['price'] * data['quantity']

In [40]:
data

  product    price  quantity    cost  total_sales
0     노트북  1200000        10  800000     12000000
1     마우스    25000        50   15000      1250000
2     키보드    80000        30   50000      2400000
3     모니터   350000        15  200000      5250000
4     스피커   120000        25   80000      3000000

In [44]:
data['profit'] = (data['price']-data['cost']) * data['quantity']

In [45]:
data

  product    price  quantity    cost  total_sales   profit
0     노트북  1200000        10  800000     12000000  4000000
1     마우스    25000        50   15000      1250000   500000
2     키보드    80000        30   50000      2400000   900000
3     모니터   350000        15  200000      5250000  2250000
4     스피커   120000        25   80000      3000000  1000000

In [49]:
data['profit_rate'] = data['profit'] / data['total_sales'] * 100

In [50]:
data

  product    price  quantity    cost  total_sales   profit  profit_rate
0     노트북  1200000        10  800000     12000000  4000000    33.333333
1     마우스    25000        50   15000      1250000   500000    40.000000
2     키보드    80000        30   50000      2400000   900000    37.500000
3     모니터   350000        15  200000      5250000  2250000    42.857143
4     스피커   120000        25   80000      3000000  1000000    33.333333

In [51]:
def classify_grade(row):
    if row['profit_rate'] >= 40:
        return 'A'

    elif row['profit_rate'] >= 35:
        return 'B'

    else:
        return 'C'

In [52]:
data.apply(classify_grade, axis=1)

0    C
1    A
2    B
3    A
4    C
dtype: str

In [53]:
data['profit_rate'].map(lambda x: 'A' if x >= 40 else 'B' if x >= 35 else 'C')

0    C
1    A
2    B
3    A
4    C
Name: profit_rate, dtype: str

In [56]:
data['profit_rate'].apply(lambda x: 'A' if x >= 40 else 'B' if x >= 35 else 'C')

0    C
1    A
2    B
3    A
4    C
Name: profit_rate, dtype: str

In [58]:
data['price'].map(lambda x: '고가' if x >= 300000 else '중가' if x >= 100000 else '저가')

0    고가
1    저가
2    저가
3    고가
4    중가
Name: price, dtype: str

In [61]:
data[['price', 'quantity', 'profit']].apply(np.mean)

price        355000.0
quantity         26.0
profit      1730000.0
dtype: float64

In [62]:
data[['price', 'quantity', 'profit']].mean(axis=0)

price        355000.0
quantity         26.0
profit      1730000.0
dtype: float64

In [63]:
data

  product    price  quantity    cost  total_sales   profit  profit_rate
0     노트북  1200000        10  800000     12000000  4000000    33.333333
1     마우스    25000        50   15000      1250000   500000    40.000000
2     키보드    80000        30   50000      2400000   900000    37.500000
3     모니터   350000        15  200000      5250000  2250000    42.857143
4     스피커   120000        25   80000      3000000  1000000    33.333333

In [64]:
data.assign(total = data.cost + data.profit)

,product,price,quantity,cost,total_sales,profit,profit_rate,total
0,노트북,1200000,10,800000,12000000,4000000,33.333333,4800000
1,마우스,25000,50,15000,1250000,500000,40.000000,515000
2,키보드,80000,30,50000,2400000,900000,37.500000,950000
3,모니터,350000,15,200000,5250000,2250000,42.857143,2450000
4,스피커,120000,25,80000,3000000,1000000,33.333333,1080000

In [67]:
data.assign(total = data.cost * 2, total2 = data.cost / 100)

,product,price,quantity,cost,total_sales,profit,profit_rate,total,total2
0,노트북,1200000,10,800000,12000000,4000000,33.333333,1600000,8000.0
1,마우스,25000,50,15000,1250000,500000,40.000000,30000,150.0
2,키보드,80000,30,50000,2400000,900000,37.500000,100000,500.0
3,모니터,350000,15,200000,5250000,2250000,42.857143,400000,2000.0
4,스피커,120000,25,80000,3000000,1000000,33.333333,160000,800.0

In [68]:
data

  product    price  quantity    cost  total_sales   profit  profit_rate
0     노트북  1200000        10  800000     12000000  4000000    33.333333
1     마우스    25000        50   15000      1250000   500000    40.000000
2     키보드    80000        30   50000      2400000   900000    37.500000
3     모니터   350000        15  200000      5250000  2250000    42.857143
4     스피커   120000        25   80000      3000000  1000000    33.333333

In [72]:
data[['price', 'quantity', 'cost']].sum()

price       1775000
quantity        130
cost        1145000
dtype: int64

In [80]:
data['grade'] = data.profit_rate.apply(lambda x: 'A급' if x >= 40 else 'B급' if x >= 35 else 'C급')

In [81]:
data

  product    price  quantity    cost  total_sales   profit  profit_rate grade
0     노트북  1200000        10  800000     12000000  4000000    33.333333    C급
1     마우스    25000        50   15000      1250000   500000    40.000000    A급
2     키보드    80000        30   50000      2400000   900000    37.500000    B급
3     모니터   350000        15  200000      5250000  2250000    42.857143    A급
4     스피커   120000        25   80000      3000000  1000000    33.333333    C급

In [86]:
data

  product    price  quantity    cost  total_sales   profit  profit_rate grade
0     노트북  1200000        10  800000     12000000  4000000    33.333333    C급
1     마우스    25000        50   15000      1250000   500000    40.000000    A급
2     키보드    80000        30   50000      2400000   900000    37.500000    B급
3     모니터   350000        15  200000      5250000  2250000    42.857143    A급
4     스피커   120000        25   80000      3000000  1000000    33.333333    C급

In [92]:
data.query('price <= 80000 or cost >= 800000')

  product    price  quantity    cost  total_sales   profit  profit_rate grade
0     노트북  1200000        10  800000     12000000  4000000    33.333333    C급
1     마우스    25000        50   15000      1250000   500000    40.000000    A급
2     키보드    80000        30   50000      2400000   900000    37.500000    B급

In [93]:
data

  product    price  quantity    cost  total_sales   profit  profit_rate grade
0     노트북  1200000        10  800000     12000000  4000000    33.333333    C급
1     마우스    25000        50   15000      1250000   500000    40.000000    A급
2     키보드    80000        30   50000      2400000   900000    37.500000    B급
3     모니터   350000        15  200000      5250000  2250000    42.857143    A급
4     스피커   120000        25   80000      3000000  1000000    33.333333    C급

In [94]:
category_mapping = {
    '노트북': '컴퓨터',
    '마우스': '주변기기',
    '키보드': '주변기기',
    '모니터': '디스플레이',
    '스피커': '오디오'
}

grade_points = {'A급': 100, 'B급': 80, 'C급': 60}

In [111]:
data['category'] = data['product'].map(category_mapping)
data

,product,price,quantity,cost,total_sales,profit,profit_rate,grade,category
0,노트북,1200000,10,800000,12000000,4000000,33.333333,C급,컴퓨터
1,마우스,25000,50,15000,1250000,500000,40.000000,A급,주변기기
2,키보드,80000,30,50000,2400000,900000,37.500000,B급,주변기기
3,모니터,350000,15,200000,5250000,2250000,42.857143,A급,디스플레이
4,스피커,120000,25,80000,3000000,1000000,33.333333,C급,오디오

In [100]:
data['product'].map(lambda x: category_mapping[x] if x in category_mapping else None)

0      컴퓨터
1     주변기기
2     주변기기
3    디스플레이
4      오디오
Name: product, dtype: str

In [101]:
None == None

True

In [105]:
type(pd.NA)

pandas.api.typing.NAType

In [106]:
pd.NA == pd.NA

In [107]:
pd.isna(pd.NA)

True

In [108]:
pd.isna(np.nan)

True

In [110]:
pd.isna('')

False

In [112]:
data

,product,price,quantity,cost,total_sales,profit,profit_rate,grade,category
0,노트북,1200000,10,800000,12000000,4000000,33.333333,C급,컴퓨터
1,마우스,25000,50,15000,1250000,500000,40.000000,A급,주변기기
2,키보드,80000,30,50000,2400000,900000,37.500000,B급,주변기기
3,모니터,350000,15,200000,5250000,2250000,42.857143,A급,디스플레이
4,스피커,120000,25,80000,3000000,1000000,33.333333,C급,오디오

In [113]:
data['grade'].map(grade_points)

0     60
1    100
2     80
3    100
4     60
Name: grade, dtype: int64

In [114]:
data['points'] = data['grade'].map(grade_points)
data

,product,price,quantity,cost,total_sales,profit,profit_rate,grade,category,points
0,노트북,1200000,10,800000,12000000,4000000,33.333333,C급,컴퓨터,60
1,마우스,25000,50,15000,1250000,500000,40.000000,A급,주변기기,100
2,키보드,80000,30,50000,2400000,900000,37.500000,B급,주변기기,80
3,모니터,350000,15,200000,5250000,2250000,42.857143,A급,디스플레이,100
4,스피커,120000,25,80000,3000000,1000000,33.333333,C급,오디오,60

In [118]:
data['is_profitable'] = np.where(data['profit'] > 1000000, '고수익', '일반수익')

In [119]:
data

,product,price,quantity,cost,total_sales,profit,profit_rate,grade,category,points,is_profitable
0,노트북,1200000,10,800000,12000000,4000000,33.333333,C급,컴퓨터,60,고수익
1,마우스,25000,50,15000,1250000,500000,40.000000,A급,주변기기,100,일반수익
2,키보드,80000,30,50000,2400000,900000,37.500000,B급,주변기기,80,일반수익
3,모니터,350000,15,200000,5250000,2250000,42.857143,A급,디스플레이,100,고수익
4,스피커,120000,25,80000,3000000,1000000,33.333333,C급,오디오,60,일반수익

In [121]:
conditions = [
    data['total_sales'] >= 10000000,
    data['total_sales'] >= 5000000,
    data['total_sales'] >= 2000000
]

choices = ['대형거래', '중형거래', '소형거래']

In [123]:
data['size'] = np.select(conditions, choices, default='미니거래')

In [124]:
data

,product,price,quantity,cost,total_sales,profit,profit_rate,grade,category,points,is_profitable,size
0,노트북,1200000,10,800000,12000000,4000000,33.333333,C급,컴퓨터,60,고수익,대형거래
1,마우스,25000,50,15000,1250000,500000,40.000000,A급,주변기기,100,일반수익,미니거래
2,키보드,80000,30,50000,2400000,900000,37.500000,B급,주변기기,80,일반수익,소형거래
3,모니터,350000,15,200000,5250000,2250000,42.857143,A급,디스플레이,100,고수익,중형거래
4,스피커,120000,25,80000,3000000,1000000,33.333333,C급,오디오,60,일반수익,소형거래

In [128]:
def transaction(row):
    if row.total_sales >= 10000000:
        return '대형거래'
    elif row.total_sales >= 5000000:
        return '중형거래'
    elif row.total_sales >= 2000000:
        return '소형거래'
    else:
        return '미니거래'

In [131]:
data['trans'] = data.apply(transaction, axis=1)

In [132]:
data

,product,price,quantity,cost,total_sales,profit,profit_rate,grade,category,points,is_profitable,size,trans
0,노트북,1200000,10,800000,12000000,4000000,33.333333,C급,컴퓨터,60,고수익,대형거래,대형거래
1,마우스,25000,50,15000,1250000,500000,40.000000,A급,주변기기,100,일반수익,미니거래,미니거래
2,키보드,80000,30,50000,2400000,900000,37.500000,B급,주변기기,80,일반수익,소형거래,소형거래
3,모니터,350000,15,200000,5250000,2250000,42.857143,A급,디스플레이,100,고수익,중형거래,중형거래
4,스피커,120000,25,80000,3000000,1000000,33.333333,C급,오디오,60,일반수익,소형거래,소형거래

In [135]:
data.drop(columns='size', inplace=True)

In [136]:
data

,product,price,quantity,cost,total_sales,profit,profit_rate,grade,category,points,is_profitable,trans
0,노트북,1200000,10,800000,12000000,4000000,33.333333,C급,컴퓨터,60,고수익,대형거래
1,마우스,25000,50,15000,1250000,500000,40.000000,A급,주변기기,100,일반수익,미니거래
2,키보드,80000,30,50000,2400000,900000,37.500000,B급,주변기기,80,일반수익,소형거래
3,모니터,350000,15,200000,5250000,2250000,42.857143,A급,디스플레이,100,고수익,중형거래
4,스피커,120000,25,80000,3000000,1000000,33.333333,C급,오디오,60,일반수익,소형거래

In [139]:
data.rename(columns={'trans':'size'}, inplace=True)

In [140]:
data

,product,price,quantity,cost,total_sales,profit,profit_rate,grade,category,points,is_profitable,size
0,노트북,1200000,10,800000,12000000,4000000,33.333333,C급,컴퓨터,60,고수익,대형거래
1,마우스,25000,50,15000,1250000,500000,40.000000,A급,주변기기,100,일반수익,미니거래
2,키보드,80000,30,50000,2400000,900000,37.500000,B급,주변기기,80,일반수익,소형거래
3,모니터,350000,15,200000,5250000,2250000,42.857143,A급,디스플레이,100,고수익,중형거래
4,스피커,120000,25,80000,3000000,1000000,33.333333,C급,오디오,60,일반수익,소형거래

In [141]:
data

,product,price,quantity,cost,total_sales,profit,profit_rate,grade,category,points,is_profitable,size
0,노트북,1200000,10,800000,12000000,4000000,33.333333,C급,컴퓨터,60,고수익,대형거래
1,마우스,25000,50,15000,1250000,500000,40.000000,A급,주변기기,100,일반수익,미니거래
2,키보드,80000,30,50000,2400000,900000,37.500000,B급,주변기기,80,일반수익,소형거래
3,모니터,350000,15,200000,5250000,2250000,42.857143,A급,디스플레이,100,고수익,중형거래
4,스피커,120000,25,80000,3000000,1000000,33.333333,C급,오디오,60,일반수익,소형거래

In [142]:
price_bins = [0, 50000, 200000, float('inf')]
labels = ['저가', '중가', '고가']

In [145]:
pd.cut(data['price'], bins=price_bins, labels=labels)

0    고가
1    저가
2    중가
3    고가
4    중가
Name: price, dtype: category
Categories (3, str): ['저가' < '중가' < '고가']

In [146]:
np.inf

inf

In [147]:
float('inf')

inf

In [149]:
float('inf') == np.inf

True

In [150]:
data

,product,price,quantity,cost,total_sales,profit,profit_rate,grade,category,points,is_profitable,size
0,노트북,1200000,10,800000,12000000,4000000,33.333333,C급,컴퓨터,60,고수익,대형거래
1,마우스,25000,50,15000,1250000,500000,40.000000,A급,주변기기,100,일반수익,미니거래
2,키보드,80000,30,50000,2400000,900000,37.500000,B급,주변기기,80,일반수익,소형거래
3,모니터,350000,15,200000,5250000,2250000,42.857143,A급,디스플레이,100,고수익,중형거래
4,스피커,120000,25,80000,3000000,1000000,33.333333,C급,오디오,60,일반수익,소형거래

In [151]:
data.groupby('category')['profit_rate'].mean()

category
디스플레이    42.857143
오디오      33.333333
주변기기     38.750000
컴퓨터      33.333333
Name: profit_rate, dtype: float64

In [154]:
data['mean_profit'] = data.groupby('category')['profit_rate'].transform('mean')

In [158]:
data.drop(['is_profitable', 'size'], axis=1, inplace=True)

In [159]:
data

,product,price,quantity,cost,total_sales,profit,profit_rate,grade,category,points,mean_profit
0,노트북,1200000,10,800000,12000000,4000000,33.333333,C급,컴퓨터,60,33.333333
1,마우스,25000,50,15000,1250000,500000,40.000000,A급,주변기기,100,38.750000
2,키보드,80000,30,50000,2400000,900000,37.500000,B급,주변기기,80,38.750000
3,모니터,350000,15,200000,5250000,2250000,42.857143,A급,디스플레이,100,42.857143
4,스피커,120000,25,80000,3000000,1000000,33.333333,C급,오디오,60,33.333333

In [160]:
data.groupby('category')['total_sales'].sum()

category
디스플레이     5250000
오디오       3000000
주변기기      3650000
컴퓨터      12000000
Name: total_sales, dtype: int64

In [162]:
data['category_total_sales'] = data.groupby('category')['total_sales'].transform('sum')

In [164]:
data['category_sales_share'] = data['total_sales'] / data['category_total_sales'] *100

In [165]:
data

,product,price,quantity,cost,total_sales,profit,profit_rate,grade,category,points,mean_profit,category_total_sales,category_sales_share
0,노트북,1200000,10,800000,12000000,4000000,33.333333,C급,컴퓨터,60,33.333333,12000000,100.000000
1,마우스,25000,50,15000,1250000,500000,40.000000,A급,주변기기,100,38.750000,3650000,34.246575
2,키보드,80000,30,50000,2400000,900000,37.500000,B급,주변기기,80,38.750000,3650000,65.753425
3,모니터,350000,15,200000,5250000,2250000,42.857143,A급,디스플레이,100,42.857143,5250000,100.000000
4,스피커,120000,25,80000,3000000,1000000,33.333333,C급,오디오,60,33.333333,3000000,100.000000