In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# 예시 데이터 생성 (전자상거래 주문 데이터)
order_data = pd.DataFrame({
    'order_id': ['ORD001', 'ORD002', 'ORD003', 'ORD004', 'ORD005', 'ORD006', 'ORD007', 'ORD008'],
    'customer_id': ['C001', 'C002', 'C001', 'C003', 'C002', 'C004', 'C001', 'C003'],
    'product_category': ['전자제품', '의류', '전자제품', '도서', '의류', '전자제품', '도서', '의류'],
    'order_amount': [150000, 45000, 320000, 25000, 67000, 89000, 35000, 52000],
    'customer_age': [28, 35, 28, 42, 35, 31, 28, 42],
    'region': ['서울', '부산', '서울', '대구', '부산', '서울', '서울', '대구'],
    'order_date': pd.to_datetime(['2024-01-15', '2024-01-16', '2024-01-18', '2024-01-20',
                                  '2024-01-22', '2024-01-25', '2024-01-28', '2024-01-30'])
})

display(order_data)

,order_id,customer_id,product_category,order_amount,customer_age,region,order_date
0,ORD001,C001,전자제품,150000,28,서울,2024-01-15
1,ORD002,C002,의류,45000,35,부산,2024-01-16
2,ORD003,C001,전자제품,320000,28,서울,2024-01-18
3,ORD004,C003,도서,25000,42,대구,2024-01-20
4,ORD005,C002,의류,67000,35,부산,2024-01-22
5,ORD006,C004,전자제품,89000,31,서울,2024-01-25
6,ORD007,C001,도서,35000,28,서울,2024-01-28
7,ORD008,C003,의류,52000,42,대구,2024-01-30

In [5]:
order_data.shape

(8, 7)

In [6]:
order_data.dtypes

order_id                       str
customer_id                    str
product_category               str
order_amount                 int64
customer_age                 int64
region                         str
order_date          datetime64[us]
dtype: object

In [7]:
order_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          8 non-null      str
 1   customer_id       8 non-null      str
 2   product_category  8 non-null      str
 3   order_amount      8 non-null      int64
 4   customer_age      8 non-null      int64
 5   region            8 non-null      str
 6   order_date        8 non-null      datetime64[us]
dtypes: datetime64[us](1), int64(2), str(4)
memory usage: 580.0 bytes

In [8]:
order_data.shape

(8, 7)

In [17]:
order_data.columns

Index(['order_id', 'customer_id', 'product_category', 'order_amount',
       'customer_age', 'region', 'order_date'],
      dtype='str')

In [10]:
order_data.index

RangeIndex(start=0, stop=8, step=1)

In [18]:
order_data.dtypes

order_id                       str
customer_id                    str
product_category               str
order_amount                 int64
customer_age                 int64
region                         str
order_date          datetime64[us]
dtype: object

In [19]:
order_data.isna().sum()

order_id            0
customer_id         0
product_category    0
order_amount        0
customer_age        0
region              0
order_date          0
dtype: int64

In [20]:
order_data.describe()

       order_amount  customer_age           order_date
count       8.00000      8.000000                    8
mean    97875.00000     33.625000  2024-01-21 18:00:00
min     25000.00000     28.000000  2024-01-15 00:00:00
25%     42500.00000     28.000000  2024-01-17 12:00:00
50%     59500.00000     33.000000  2024-01-21 00:00:00
75%    104250.00000     36.750000  2024-01-25 18:00:00
max    320000.00000     42.000000  2024-01-30 00:00:00
std     98018.12879      5.926635                  NaN

In [22]:
order_data['product_category'].value_counts()

product_category
전자제품    3
의류      3
도서      2
Name: count, dtype: int64

In [23]:
order_data['region'].value_counts()

region
서울    4
부산    2
대구    2
Name: count, dtype: int64

In [25]:
order_data['order_amount'].agg(['mean', 'median', 'std', 'min', 'max', 'count'])

mean       97875.00000
median     59500.00000
std        98018.12879
min        25000.00000
max       320000.00000
count          8.00000
Name: order_amount, dtype: float64

In [26]:
order_data['order_amount'].quantile([0.25, 0.5, 0.75,0.9])

0.25     42500.0
0.50     59500.0
0.75    104250.0
0.90    201000.0
Name: order_amount, dtype: float64

In [27]:
order_data['order_amount'].describe()

count         8.00000
mean      97875.00000
std       98018.12879
min       25000.00000
25%       42500.00000
50%       59500.00000
75%      104250.00000
max      320000.00000
Name: order_amount, dtype: float64

In [30]:
order_data[['customer_age', 'order_amount']].corr()

              customer_age  order_amount
customer_age      1.000000     -0.559552
order_amount     -0.559552      1.000000

In [38]:
# 지역별, 카테고리별 평균 주문금액 피봇테이블
region_category_pivot = pd.pivot_table(
    order_data,
    values='order_amount',
    index='region',
    columns='product_category',
    aggfunc='mean',
    fill_value=0
)

print("=== 지역별 카테고리별 평균 주문금액 ===")
print(region_category_pivot)

=== 지역별 카테고리별 평균 주문금액 ===
product_category       도서       의류           전자제품
region
대구                25000.0  52000.0       0.000000
부산                    0.0  56000.0       0.000000
서울                35000.0      0.0  186333.333333

In [34]:
order_data[['order_amount', 'region', 'product_category']]

   order_amount region product_category
0        150000     서울             전자제품
1         45000     부산               의류
2        320000     서울             전자제품
3         25000     대구               도서
4         67000     부산               의류
5         89000     서울             전자제품
6         35000     서울               도서
7         52000     대구               의류

In [42]:
order_data.groupby(['region', 'product_category'])['order_amount'].mean().unstack()

product_category       도서       의류           전자제품
region
대구                25000.0  52000.0            NaN
부산                    NaN  56000.0            NaN
서울                35000.0      NaN  186333.333333

In [45]:
# 다중 집계 함수 적용
multi_agg_pivot = pd.pivot_table(
    order_data,
    values='order_amount',
    index='region',
    columns='product_category',
    aggfunc=['mean', 'count', 'sum'],
    fill_value=0,
    margins=True  # 총합 행/열 추가
)

print("=== 다중 집계 함수 피봇테이블 (일부) ===")
print(multi_agg_pivot)  # 평균값만 출력

=== 다중 집계 함수 피봇테이블 (일부) ===
                     mean                                        count     \
product_category       도서            의류           전자제품       All    도서 의류
region
대구                25000.0  52000.000000       0.000000   38500.0     1  1
부산                    0.0  56000.000000       0.000000   56000.0     0  2
서울                35000.0      0.000000  186333.333333  148500.0     1  0
All               30000.0  54666.666667  186333.333333   97875.0     2  3

                             sum
product_category 전자제품 All     도서      의류    전자제품     All
region
대구                  0   2  25000   52000       0   77000
부산                  0   2      0  112000       0  112000
서울                  3   4  35000       0  559000  594000
All                 3   8  60000  164000  559000  783000

In [47]:
order_data

,order_id,customer_id,product_category,order_amount,customer_age,region,order_date
0,ORD001,C001,전자제품,150000,28,서울,2024-01-15
1,ORD002,C002,의류,45000,35,부산,2024-01-16
2,ORD003,C001,전자제품,320000,28,서울,2024-01-18
3,ORD004,C003,도서,25000,42,대구,2024-01-20
4,ORD005,C002,의류,67000,35,부산,2024-01-22
5,ORD006,C004,전자제품,89000,31,서울,2024-01-25
6,ORD007,C001,도서,35000,28,서울,2024-01-28
7,ORD008,C003,의류,52000,42,대구,2024-01-30

In [51]:
order_data['age_group'] = pd.cut(order_data['customer_age'], bins=[0, 30, 40, 50, np.inf], labels = ['20대', '30대', '40대', '50대 이상'])

In [52]:
order_data

,order_id,customer_id,product_category,order_amount,customer_age,region,order_date,age_group
0,ORD001,C001,전자제품,150000,28,서울,2024-01-15,20대
1,ORD002,C002,의류,45000,35,부산,2024-01-16,30대
2,ORD003,C001,전자제품,320000,28,서울,2024-01-18,20대
3,ORD004,C003,도서,25000,42,대구,2024-01-20,40대
4,ORD005,C002,의류,67000,35,부산,2024-01-22,30대
5,ORD006,C004,전자제품,89000,31,서울,2024-01-25,30대
6,ORD007,C001,도서,35000,28,서울,2024-01-28,20대
7,ORD008,C003,의류,52000,42,대구,2024-01-30,40대

In [57]:
pd.pivot_table(order_data, values='order_amount', index='age_group', columns='region', aggfunc='mean')

region          대구       부산             서울
age_group
20대            NaN      NaN  168333.333333
30대            NaN  56000.0   89000.000000
40대        38500.0      NaN            NaN

In [56]:
# 고객 연령대별, 지역별 주문 건수
order_data['age_group'] = pd.cut(order_data['customer_age'],
                                bins=[0, 30, 40, 50],
                                labels=['20대', '30대', '40대'])

age_region_pivot = pd.pivot_table(
    order_data,
    values='order_id',
    index='age_group',
    columns='region',
    aggfunc='count',
    fill_value=0
)

print("=== 연령대별 지역별 주문 건수 ===")
print(age_region_pivot)

=== 연령대별 지역별 주문 건수 ===
region     대구  부산  서울
age_group
20대         0   0   3
30대         0   2   1
40대         2   0   0

In [62]:
order_data

,order_id,customer_id,product_category,order_amount,customer_age,region,order_date,age_group
0,ORD001,C001,전자제품,150000,28,서울,2024-01-15,20대
1,ORD002,C002,의류,45000,35,부산,2024-01-16,30대
2,ORD003,C001,전자제품,320000,28,서울,2024-01-18,20대
3,ORD004,C003,도서,25000,42,대구,2024-01-20,40대
4,ORD005,C002,의류,67000,35,부산,2024-01-22,30대
5,ORD006,C004,전자제품,89000,31,서울,2024-01-25,30대
6,ORD007,C001,도서,35000,28,서울,2024-01-28,20대
7,ORD008,C003,의류,52000,42,대구,2024-01-30,40대

In [66]:
order_data.groupby(['age_group', 'region'])['order_amount'].mean().unstack()

region          대구       부산             서울
age_group
20대            NaN      NaN  168333.333333
30대            NaN  56000.0   89000.000000
40대        38500.0      NaN            NaN

In [67]:
# 고객별 주문 통계
customer_stats = order_data.groupby('customer_id').agg({
    'order_amount': ['count', 'sum', 'mean', 'max'],
    'order_id': 'count'
}).round(2)

display(customer_stats)

            order_amount                            order_id
                   count     sum       mean     max    count
customer_id
C001                   3  505000  168333.33  320000        3
C002                   2  112000   56000.00   67000        2
C003                   2   77000   38500.00   52000        2
C004                   1   89000   89000.00   89000        1

In [70]:
import yfinance as yf

In [69]:
%pip install yfinance

Collecting yfinance
  Downloading yfinance-1.5.1-py2.py3-none-any.whl.metadata (6.2 kB)
Requirement already satisfied: pandas>=1.3.0 in c:\ajb\git\big0611\.venv\lib\site-packages (from yfinance) (3.0.3)
Requirement already satisfied: numpy>=1.16.5 in c:\ajb\git\big0611\.venv\lib\site-packages (from yfinance) (2.4.6)
Collecting requests>=2.31 (from yfinance)
  Downloading requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Collecting multitasking>=0.0.7 (from yfinance)
  Downloading multitasking-0.0.13-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: platformdirs>=2.0.0 in c:\ajb\git\big0611\.venv\lib\site-packages (from yfinance) (4.10.0)
Collecting pytz>=2022.5 (from yfinance)
  Downloading pytz-2026.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting peewee>=3.16.2 (from yfinance)
  Downloading peewee-4.1.1-py3-none-any.whl.metadata (10 kB)
Collecting beautifulsoup4>=4.11.1 (from yfinance)
  Downloading beautifulsoup4-4.15.0-py3-none-any.whl.metadata (3.8 kB)
Collecting curl_cffi>=0.15 (from yfinance)
  Downloading curl_cffi-0.15.0-cp310-abi3-win_amd64.whl.metadata (18 kB)
Collecting protobuf>=3.19.0 (from yfinance)
  Downloading protobuf-7.35.1-cp310-abi3-win_amd64.whl.metadata (595 bytes)
Collecting websockets>=13.0 (from yfinance)
  Downloading websockets-16.0-cp311-cp311-win_amd64.whl.metadata (7.0 kB)
Collecting soupsieve>=1.6.1 (from beautifulsoup4>=4.11.1->yfinance)
  Downloading soupsieve-2.8.4-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\ajb\git\big0611\.venv\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Collecting cffi>=2.0.0 (from curl_cffi>=0.15->yfinance)
  Downloading cffi-2.1.0-cp311-cp311-win_amd64.whl.metadata (2.6 kB)
Collecting certifi>=2024.2.2 (from curl_cffi>=0.15->yfinance)
  Downloading certifi-2026.6.17-py3-none-any.whl.metadata (2.5 kB)
Collecting rich (from curl_cffi>=0.15->yfinance)
  Downloading rich-15.0.0-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\ajb\git\big0611\.venv\lib\site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\ajb\git\big0611\.venv\lib\site-packages (from pandas>=1.3.0->yfinance) (2026.2)
Collecting charset_normalizer<4,>=2 (from requests>=2.31->yfinance)
  Downloading charset_normalizer-3.4.8-cp311-cp311-win_amd64.whl.metadata (42 kB)
     ---------------------------------------- 0.0/42.3 kB ? eta -:--:--
     ---------------------------------------- 42.3/42.3 kB ? eta 0:00:00
Collecting idna<4,>=2.5 (from requests>=2.31->yfinance)
  Downloading idna-3.18-py3-none-any.whl.metadata (6.1 kB)
Collecting urllib3<3,>=1.26 (from requests>=2.31->yfinance)
  Using cached urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Collecting pycparser (from cffi>=2.0.0->curl_cffi>=0.15->yfinance)
  Downloading pycparser-3.0-py3-none-any.whl.metadata (8.2 kB)
Requirement already satisfied: six>=1.5 in c:\ajb\git\big0611\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Collecting markdown-it-py>=2.2.0 (from rich->curl_cffi>=0.15->yfinance)
  Downloading markdown_it_py-4.2.0-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\ajb\git\big0611\.venv\lib\site-packages (from rich->curl_cffi>=0.15->yfinance) (2.20.0)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich->curl_cffi>=0.15->yfinance)
  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Downloading yfinance-1.5.1-py2.py3-none-any.whl (144 kB)
   ---------------------------------------- 0.0/144.2 kB ? eta -:--:--
   ---------------------------------------- 144.2/144.2 kB 8.9 MB/s eta 0:00:00
Downloading beautifulsoup4-4.15.0-py3-none-any.whl (109 kB)
   ---------------------------------------- 0.0/109.9 kB ? eta -:--:--
   ---------------------------------------- 109.9/109.9 kB ? eta 0:00:00
Downloading curl_cffi-0.15.0-cp310-abi3-win_amd64.whl (1.7 MB)
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ------------ --------------------------- 0.5/1.7 MB 10.9 MB/s eta 0:00:01
   ------------------------------ --------- 1.3/1.7 MB 11.4 MB/s eta 0:00:01
   ---------------------------------------- 1.7/1.7 MB 11.7 MB/s eta 0:00:00
Downloading multitasking-0.0.13-py3-none-any.whl (16 kB)
Downloading peewee-4.1.1-py3-none-any.whl (170 kB)
   ---------------------------------------- 0.0/170.3 kB ? eta -:--:--
   ---------------------------------------- 170.3/170.3 kB ? eta 0:00:00
Downloading protobuf-7.35.1-cp310-abi3-win_amd64.whl (439 kB)
   ---------------------------------------- 0.0/440.0 kB ? eta -:--:--
   ----------------------------- --------- 327.7/440.0 kB 10.2 MB/s eta 0:00:01
   ---------------------------------------- 440.0/440.0 kB 9.3 MB/s eta 0:00:00
Downloading pytz-2026.2-py2.py3-none-any.whl (510 kB)
   ---------------------------------------- 0.0/510.1 kB ? eta -:--:--
   -------------------------------- ------- 409.6/510.1 kB 8.5 MB/s eta 0:00:01
   --------------------------------------- 510.1/510.1 kB 10.6 MB/s eta 0:00:00
Downloading requests-2.34.2-py3-none-any.whl (73 kB)
   ---------------------------------------- 0.0/73.1 kB ? eta -:--:--
   ---------------------------------------- 73.1/73.1 kB 4.2 MB/s eta 0:00:00
Downloading websockets-16.0-cp311-cp311-win_amd64.whl (178 kB)
   ---------------------------------------- 0.0/178.7 kB ? eta -:--:--
   ---------------------------------------- 178.7/178.7 kB 5.4 MB/s eta 0:00:00
Downloading certifi-2026.6.17-py3-none-any.whl (133 kB)
   ---------------------------------------- 0.0/133.3 kB ? eta -:--:--
   ---------------------------------------- 133.3/133.3 kB 7.7 MB/s eta 0:00:00
Downloading cffi-2.1.0-cp311-cp311-win_amd64.whl (185 kB)
   ---------------------------------------- 0.0/185.1 kB ? eta -:--:--
   --------------------------------------- 185.1/185.1 kB 11.7 MB/s eta 0:00:00
Downloading charset_normalizer-3.4.8-cp311-cp311-win_amd64.whl (161 kB)
   ---------------------------------------- 0.0/161.2 kB ? eta -:--:--
   ---------------------------------------- 161.2/161.2 kB 9.4 MB/s eta 0:00:00
Downloading idna-3.18-py3-none-any.whl (65 kB)
   ---------------------------------------- 0.0/65.5 kB ? eta -:--:--
   ---------------------------------------- 65.5/65.5 kB 3.7 MB/s eta 0:00:00
Downloading soupsieve-2.8.4-py3-none-any.whl (37 kB)
Using cached urllib3-2.7.0-py3-none-any.whl (131 kB)
Downloading rich-15.0.0-py3-none-any.whl (310 kB)
   ---------------------------------------- 0.0/310.7 kB ? eta -:--:--
   --------------------------------------- 310.7/310.7 kB 18.8 MB/s eta 0:00:00
Downloading markdown_it_py-4.2.0-py3-none-any.whl (91 kB)
   ---------------------------------------- 0.0/91.7 kB ? eta -:--:--
   ---------------------------------------- 91.7/91.7 kB 5.1 MB/s eta 0:00:00
Downloading pycparser-3.0-py3-none-any.whl (48 kB)
   ---------------------------------------- 0.0/48.2 kB ? eta -:--:--
   ---------------------------------------- 48.2/48.2 kB ? eta 0:00:00
Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Installing collected packages: pytz, peewee, multitasking, websockets, urllib3, soupsieve, pycparser, protobuf, mdurl, idna, charset_normalizer, certifi, requests, markdown-it-py, cffi, beautifulsoup4, rich, curl_cffi, yfinance
Successfully installed beautifulsoup4-4.15.0 certifi-2026.6.17 cffi-2.1.0 charset_normalizer-3.4.8 curl_cffi-0.15.0 idna-3.18 markdown-it-py-4.2.0 mdurl-0.1.2 multitasking-0.0.13 peewee-4.1.1 protobuf-7.35.1 pycparser-3.0 pytz-2026.2 requests-2.34.2 rich-15.0.0 soupsieve-2.8.4 urllib3-2.7.0 websockets-16.0 yfinance-1.5.1
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip