### 결측치 처리
결측치?  
데이터 수집 문제 또는 데이터 입력 오류와 같은 다양한 이유로 관측되어야 할 값을 얻지 못한 데이터

In [2]:
import pandas as pd
import numpy as np

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, np.nan, 35, 30],         # Bob의 나이 결측치
    'Salary': [5000, 4000, np.nan, 6000] # Charlie의 급여 결측치
}
df = pd.DataFrame(data)

In [7]:
a = np.array([0,1,2,3,4,5,6,7,8,10000])

In [8]:
a

array([    0,     1,     2,     3,     4,     5,     6,     7,     8,
       10000])

In [9]:
np.median(a)

np.float64(4.5)

In [10]:
np.mean(a)

np.float64(1003.6)

In [11]:
df

      Name   Age  Salary
0    Alice  25.0  5000.0
1      Bob   NaN  4000.0
2  Charlie  35.0     NaN
3    David  30.0  6000.0

In [12]:
df.dropna()

    Name   Age  Salary
0  Alice  25.0  5000.0
3  David  30.0  6000.0

In [13]:
df

      Name   Age  Salary
0    Alice  25.0  5000.0
1      Bob   NaN  4000.0
2  Charlie  35.0     NaN
3    David  30.0  6000.0

In [15]:
df.dropna(axis=1)

      Name
0    Alice
1      Bob
2  Charlie
3    David

In [17]:
df.dropna(subset=['Salary'])

    Name   Age  Salary
0  Alice  25.0  5000.0
1    Bob   NaN  4000.0
3  David  30.0  6000.0

In [18]:
df

      Name   Age  Salary
0    Alice  25.0  5000.0
1      Bob   NaN  4000.0
2  Charlie  35.0     NaN
3    David  30.0  6000.0