In [1]:
import numpy as np
import pandas as pd

In [2]:
# 샘플 데이터 생성
df_user = pd.DataFrame({'id': [1, 2, 3], 'name': ['Alice', 'Bob', 'Charlie']})
df_order = pd.DataFrame({'id': [1, 2, 4], 'product': ['Notebook', 'Mouse', 'Monitor']})

# 'id' 컬럼을 기준으로 왼쪽(df_user) 데이터 기준 병합 (가장 많이 씀!)
merged_df = pd.merge(df_user, df_order, on='id', how='left')
print(merged_df)

   id     name   product
0   1    Alice  Notebook
1   2      Bob     Mouse
2   3  Charlie       NaN

In [4]:
df_order

   id   product
0   1  Notebook
1   2     Mouse
2   4   Monitor

In [6]:
pd.merge(df_user, df_order, on='id', how='outer')

   id     name   product
0   1    Alice  Notebook
1   2      Bob     Mouse
2   3  Charlie       NaN
3   4      NaN   Monitor

In [7]:
# 샘플 데이터 생성 (1월 매출과 2월 매출 데이터)
df_jan = pd.DataFrame({'sales': [100, 150], 'profit': [10, 15]}, index=['Prod_A', 'Prod_B'])
df_feb = pd.DataFrame({'sales': [120, 170], 'profit': [12, 18]}, index=['Prod_A', 'Prod_B'])

# 위아래로 데이터 이어붙이기
total_sales = pd.concat([df_jan, df_feb], axis=0)
print(total_sales)

        sales  profit
Prod_A    100      10
Prod_B    150      15
Prod_A    120      12
Prod_B    170      18

In [8]:
df_jan

        sales  profit
Prod_A    100      10
Prod_B    150      15

In [9]:
df_feb

        sales  profit
Prod_A    120      12
Prod_B    170      18

In [13]:
pd.concat([df_jan, df_feb], axis=1)

        sales  profit  sales  profit
Prod_A    100      10    120      12
Prod_B    150      15    170      18